### ISSUE TITLE
Appveyor CI tests - Xml Validator

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#10]
We should run this automatically for every commit.

**Comment by alberts2** [comment]
The XmlValidator.exe in Tools now has a automated mode which requires no user input it can be activated with -a in the command line.

**Comment by billw2012** [comment]
Cool, I'm not making Appveyor stuff high prio, it can be done after SVN switchover (hence the Post SVN switchover Milestone 😄 ).

**Comment by billw2012** [comment]
This will run in AppVeyor now, once it can get past the code builds. I will export my online config to a appveyor.yaml soon.
