### ISSUE TITLE
Out of sync errors possibly related to build queue

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#102]
Details here:
https://forums.civfanatics.com/threads/caveman-2-cosmos.288570/page-661#post-15536469
https://forums.civfanatics.com/threads/caveman-2-cosmos.288570/page-663#post-15538260

**Comment by billw2012** [comment]
@Toffer90 You reckon this was the one you fixed? Or is the build queue a different one again?

**Comment by alberts2** [comment]
I'am not sure if it even was the build queue itself causing this or the automatic unit naming when creating a unit. Needs to be tested with unit naming disabled.

**Comment by Toffer90** [comment]
@billw2012  If there was/is an OOS issue with the build queue then I know for a fact I didn't fix it yet.

**Comment by Thunderbrd** [comment]
I don't THINK it's the unit naming.  The sync reports have always shown differences in those, even showing that the game could run for many rounds without an OOS with that issue in effect, so I think it's a harmless matter.

**Comment by Thunderbrd** [comment]
FYI, I'll look into this as much as I can and will help in every way possible but we really can't release v40 until this is solved.

**Comment by Toffer90** [comment]
What exactly is the OOSLog difference when this OOS occur, probably different production in a city I guess, but it should be verified with the logs anyhow.

**Comment by Thunderbrd** [comment]
Yeah, ok, I'll work with Whisperr to get her logs tomorrow as we're about to go to bed here now.  Once I get her logs I can do the compare to confirm.

**Comment by alberts2** [comment]
The unit naming should be turned of otherwise you get OOS problems very soon.

There was a OOS introduced in the new production popup that is fixed now. Could using that popup to choose the next thing to produce caused your OOS?

**Comment by Thunderbrd** [comment]
Happy to have the unit naming turned off - not sure how - though the OOS logs have shown unit names to differ on each computer safely for a while now so I'm surprised you're finding it's an actual cause for an OOS.  My wife was not using the popup to make her selection - in fact the popup wasn't even coming up for her apparently.  She doesn't remember getting the popup at all even when she founded the city.  She could be wrong about that.  We'll do a little more testing later when we can.

**Comment by alberts2** [comment]
You are right the unit naming doesn't lead to a OOS because the unit names would even be different if players play with different languages.
At the start of a new game a few different OOS problems occured and the production popup OOS took a while to figure so i might have just falsely blamed the unit naming.

**Comment by Thunderbrd** [comment]
We'll run some more tests tonight I think and hopefully have some more data to work with.  @Alberts2: are you running test simultaneous turn MP games on your own there?  Nice capacity to have.

**Comment by alberts2** [comment]
I recently did a few tests running multiple instances of c2c on my laptop because for a long time we didn't work on OOS problems. For the V40 release some work to improve multiplayer games would be nice.

**Comment by Thunderbrd** [comment]
Strongly agree!

**Comment by Thunderbrd** [comment]
Seriously?  No support for 7zip files?  Wtf Git?  Checkout the post on the forum then please.  We had a new sudden OOS having something to do with a religion name as soon as we entered the game but I THINK we were able to get a little info on this one.  Maybe.  Maybe couldn't get that far due to the new OOS error.  We're moving the wrong direction here.  lol

**Comment by alberts2** [comment]
There was a error in OOSLogger.writeLog that should be fixed in https://github.com/caveman2cosmos/Caveman2Cosmos/commit/c235ae301c82d7032eadd927d56e8662578c8435 and you two played with different versions of C2C.

**Comment by billw2012** [comment]
Okay closing this, build queue must be fine now.
