### ISSUE TITLE
Turn 0 OOS - Pangaea Huge 18 AI

### ISSUE THREAD

**Issue by Mouse** [caveman2cosmos/Caveman2Cosmos#1036]
Latest SVN version on both clients, Direct IP Connection, Cache cleared on both clients before startup each time, simultaneous turns disabled, random events disabled,

I am Client 
![Civ4BeyondSword_KmWkHNCs3L](https://user-images.githubusercontent.com/1778849/122468774-be937e00-cf81-11eb-9f59-46451e002902.png)

Hosts perspective
![unknown](https://user-images.githubusercontent.com/1778849/122469487-a2441100-cf82-11eb-8e62-e05e8d7dcf12.png)

We live in the same house playing on 2 different PC's. Here are the specs of both if it matters. Using a Netgear Nighthawk C7800 cable router/modem combo to connect.
[DxDiag-Host.txt](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673090/DxDiag-Host.txt)
[DxDiag-Client.txt](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673091/DxDiag-Client.txt)

no savegame available considering its turn 0. No OOS log, or I don't know where to find them.

**Comment by Toffer90** [comment]
Does it happen on World mapscript too?
Tested any other mapscripts in this regard?

**Comment by Mouse** [comment]
We've only tried to play on Pangaea so far.

**Comment by Mouse** [comment]
Here are the current settings that I'm using. Apologies for the large amount of images.
![settings- (6)](https://user-images.githubusercontent.com/1778849/122472138-ca813f00-cf85-11eb-9da6-6e20697aebae.png)
![settings- (7)](https://user-images.githubusercontent.com/1778849/122472139-cb19d580-cf85-11eb-8bb9-5721244151e2.png)
![settings- (8)](https://user-images.githubusercontent.com/1778849/122472140-cb19d580-cf85-11eb-8585-e56003175339.png)
![settings- (1)](https://user-images.githubusercontent.com/1778849/122472141-cb19d580-cf85-11eb-9c08-a5673d32d0b5.png)
![settings- (2)](https://user-images.githubusercontent.com/1778849/122472143-cb19d580-cf85-11eb-8dd0-1e78a4e14816.png)
![settings- (3)](https://user-images.githubusercontent.com/1778849/122472144-cbb26c00-cf85-11eb-9b07-8efe91c09804.png)
![settings- (4)](https://user-images.githubusercontent.com/1778849/122472145-cbb26c00-cf85-11eb-9a63-cb728e185d94.png)
![settings- (5)](https://user-images.githubusercontent.com/1778849/122472147-cbb26c00-cf85-11eb-9c4b-a1348ee9484c.png)

**Comment by MattOttawa** [comment]
Can you turn on python error messages in bts config file and repost the first screenshot?

**Comment by Toffer90** [comment]
> No OOS log, or I don't know where to find them.

should be here:
USERNAME\Documents\My Games\Beyond the Sword\Logs

**Comment by Mouse** [comment]
loggingenabled = 1
hidepythonexceptions = 0

I hope those were the correct settings. Here are each of our logs directories
[Logs-Client.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673307/Logs-Client.zip)
[Logs-Host.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673308/Logs-Host.zip)

**Comment by Toffer90** [comment]
These two as well perhaps:
synchlog = 1
randlog = 1

**Comment by Mouse** [comment]
loggingenabled = 1
hidepythonexceptions = 0
synchlog = 1
randlog = 1

Here are the new log files.
[Logs-Client.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673330/Logs-Client.zip)
[Logs-Host.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673331/Logs-Host.zip)

**Comment by Toffer90** [comment]
This time it is clear that you got different maps, which makes the pangea mapscript a big suspect.
![image](https://user-images.githubusercontent.com/54038029/122475811-7b5afe80-cfc5-11eb-851d-de547efb8db0.png)

**Comment by Mouse** [comment]
Is there any other information I can provide to help or is it all up to the code now?

**Comment by Toffer90** [comment]
> Is there any other information I can provide to help or is it all up to the code now?

Could you check if it happens on the world mapscript too?

Another thing, have one of you deleted the arbora mapscript?
![image](https://user-images.githubusercontent.com/54038029/122476326-47340d80-cfc6-11eb-8d6a-41a74bfcba39.png)

**Comment by Mouse** [comment]
We're both on revision 11343. Just updated to make sure. No changes.
![CurrentRevision-Client](https://user-images.githubusercontent.com/1778849/122476601-1d5df500-cf8c-11eb-98bb-cca21e676e0a.png)
![CurrentRevision-Host](https://user-images.githubusercontent.com/1778849/122476602-1d5df500-cf8c-11eb-802d-9792629f0380.png)

**Comment by Mouse** [comment]
We tried a match on C2C_World as well. Same issue.

Map settings:
![unknown (6)](https://user-images.githubusercontent.com/1778849/122477745-d7a22c00-cf8d-11eb-8345-4b764c14efa3.png)

Here are the logs
[Logs-host.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673422/Logs-host.zip)
[Logs-Client.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673423/Logs-Client.zip)

**Comment by Toffer90** [comment]
Map generation is obviously playing out differently for you two.
The info you provided might be helpful.

For now you two just have to accept that when starting a new game you both have to restart the game and load the initial save from turn 0 that you made after map gen.

**Comment by Mouse** [comment]
This time, after running on C2C_World, both the client and the host got spammed with Python Exception message boxes. The PythonErr.log file is quite large on both devices now. The host had to restart the computer because the process hung. We don't know if the log is complete. Same settings as before.

Logs here:
[Logs-Client.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673497/Logs-Client.zip)
[Logs-Host.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673498/Logs-Host.zip)

Image taken from host computer before the process hung:
![HOST-ERROR](https://user-images.githubusercontent.com/1778849/122480190-fefaf800-cf91-11eb-8fa6-5b67487f9249.png)

**Comment by Toffer90** [comment]
Could you guys test something for me, both of you add this test mapscript into your privateMaps folder, and try starting a new MP game with that script; and upload the logs again?
[C2C_World_OOS_TEST.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673543/C2C_World_OOS_TEST.zip)

**Comment by Mouse** [comment]
Here are the settings we used for that (default):
![unknown (6)](https://user-images.githubusercontent.com/1778849/122481938-3f0faa00-cf95-11eb-86b8-373cc2da9460.png)

Here are the logs and the savegames as well just in case they can help.
[Logs-Host.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673581/Logs-Host.zip)
[Logs-Client.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673578/Logs-Client.zip)
[OOS_Savefiles_CLIENTHOST.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673582/OOS_Savefiles_CLIENTHOST.zip)

**Comment by Toffer90** [comment]
You don't have to screenshot the settings anymore btw.

Could you do the same test again with this test script (yes I added different debugging to it this time)
[C2C_World_OOS_TEST.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673617/C2C_World_OOS_TEST.zip)

**Comment by Mouse** [comment]
Alright. And here you go:
[Logs-CLIENT.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673639/Logs-CLIENT.zip)
[Logs-HOST.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673640/Logs-HOST.zip)

**Comment by Toffer90** [comment]
This is just weird, you guys are out of sync even before map generation has started...
![image](https://user-images.githubusercontent.com/54038029/122483276-7fd9e400-cfd2-11eb-90bc-2d20cc476cee.png)

**Comment by Mouse** [comment]
What could that mean? Should we reinstall our copies of Civ and C2C and try again just to make sure?

**Comment by Toffer90** [comment]
> What could that mean? Should we reinstall our copies of Civ and C2C and try again just to make sure?

Try doing the SVN→Cleanup command, right click SVN folder to find it.

Could you test one last time first though, added debug lines to the absolute first code line in the mapscript that is processed when hitting launch game.
[C2C_World_OOS_TEST.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673658/C2C_World_OOS_TEST.zip)

**Comment by Mouse** [comment]
Yep. Here are the logs for that. We're going to do the cleanup command now and we'll post logs again afterward:
[Logs-Client.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673676/Logs-Client.zip)
[Logs-HOST.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673677/Logs-HOST.zip)

**Comment by Toffer90** [comment]
Heh, at the very beginning you are in sync; good that I found a point where that was the case.
May I call on you two to do more test another day, it's getting real late for me here (01:35), and the next test would have to involve me compiling a new dll for you two to use.

**Comment by Mouse** [comment]
Of course. 
And here's the results of the last test after the cleanup. Also, The cleanup command removed the UserSettings folder for both of us and it was regenerated by the game. We'll check back tomorrow. Thanks for taking the time.

[Logs-CLIENT.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673708/Logs-CLIENT.zip)
[Logs-HOST.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673709/Logs-HOST.zip)

**Comment by Toffer90** [comment]
Thank for helping out.

> The cleanup command removed the UserSettings folder for both of us

They should then be identical, so no need to share them at that point.

**Comment by Mouse** [comment]
Okay. Just for consistency, we shared the usersettings folder. Host to client and still got an OOS on turn 0
[Logs-CLIENT.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673728/Logs-CLIENT.zip)
[Logs-HOST.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6673729/Logs-HOST.zip)

**Comment by Toffer90** [comment]
Could you run the test again with this mapscript and dll file?
Replace current dll in Caveman2Cosmos/Assets
[TEST.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6679458/TEST.zip)

**Comment by Mouse** [comment]
We'll test it in the morning. It is a little late here. Sorry about that.

**Comment by Mouse** [comment]
Using that dll, the mod no longer loads. It crashes upon the initialization splash screen.

**Comment by Toffer90** [comment]
Ah, right, I forgot you were on SVN, not on latest git, I based that dll on a newer version than what is currently available on SVN.
Sorry about that fluke.

**Comment by Toffer90** [comment]
Here you go:
[TEST.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6682212/TEST.zip)

**Comment by Mouse** [comment]
Using the DLL, we can no longer connect to each other and the host's game hangs when he tries to exit the lobby after I attempt to connect and timeout. The default game still functions as expected, so it's not networking settings on our end that we know. The network log on the host does have one error line:

"We are broadcasting a public host, but have not initialized public host tools!"

This is the host's network log:
[network-2056-HOST.txt](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6684277/network-2056-HOST.txt)

**Comment by Toffer90** [comment]
That's strange, all I did was add some extra logging.
Well, I also compiled a debug dll instead of a regular release compile, meaning a lot of extra "debug" code that is normally ignored by the compiler is included in the dll.
Here's a release dll with the extra logging: [CvGameCoreDLL.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6686089/CvGameCoreDLL.zip)

Our debug dll must have worked in MP at some point as it has specific multiplayer debug code as well.

**Comment by Mouse** [comment]
Alright, we can connect again.

Getting a python error before the map finishes loading: C2C_World_OOS_TEST:4331 ('GC' is not defined). Logs included
[Logs-CLIENT.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6689046/Logs-CLIENT.zip)
[Logs-HOST.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6689047/Logs-HOST.zip)

**Comment by Toffer90** [comment]
Again?
[TEST.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6689843/TEST.zip)

**Comment by Mouse** [comment]
We've been using the release_original_unsupported like we're supposed to. The newest map and dll you sent loaded all the way until the OOS on turn 0. Here are the logs we have.

[Logs-CLIENT.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6689892/Logs-CLIENT.zip)
[Logs-HOST.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6689893/Logs-HOST.zip)

**Comment by Toffer90** [comment]
Ok, I've pinpointed a for loop where you guys go out of sync; now I have to figure out why and how to fix it.
```cpp
	for (int iI = MAX_PC_PLAYERS; iI < MAX_PLAYERS-1; iI++)
	{
		PlayerTypes ePlayer = (PlayerTypes)iI;

		FAssertMsg(!GET_PLAYER(ePlayer).isAlive(), "NPC is not expected to be alive at this point of the game initialization.");

		if (ePlayer == BEAST_PLAYER)
		{
			addPlayer(
				ePlayer, (LeaderHeadTypes)GC.getDefineINT("ANIMAL_LEADER"),
				(CivilizationTypes)GC.getDefineINT("BEAST_CIVILIZATION"), false
			);
			GET_PLAYER(ePlayer).setNewPlayerAlive(true);
			GET_TEAM(BEAST_TEAM).init(BEAST_TEAM);
			GC.getInitCore().setTeam(ePlayer, BEAST_TEAM);
			GC.getInitCore().setHandicap(ePlayer, (HandicapTypes)GC.getDefineINT("BARBARIAN_HANDICAP"));
		}
		else if (ePlayer == PREDATOR_PLAYER)
		{
			addPlayer(
				ePlayer, (LeaderHeadTypes)GC.getDefineINT("ANIMAL_LEADER"),
				(CivilizationTypes)GC.getDefineINT("PREDATOR_CIVILIZATION"), false
			);
			GET_PLAYER(ePlayer).setNewPlayerAlive(true);
			GET_TEAM(PREDATOR_TEAM).init(PREDATOR_TEAM);
			GC.getInitCore().setTeam(ePlayer, PREDATOR_TEAM);
			GC.getInitCore().setHandicap(ePlayer, (HandicapTypes)GC.getDefineINT("BARBARIAN_HANDICAP"));
		}
		else if ....
```

**Comment by Mouse** [comment]
Interesting - So, as animals and barbarians are being initialized and set alive? Are those counted as players? I just want to know.

**Comment by Toffer90** [comment]
> Interesting - So, as animals and barbarians are being initialized and set alive? Are those counted as players? I just want to know.

Yeah, something is obviously not MP friendly with the way we initialize the NPC factions, and yes they count as players/teams in their own right.

**Comment by Toffer90** [comment]
Another test? 
[CvGameCoreDLL.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6696458/CvGameCoreDLL.zip)

**Comment by Mouse** [comment]
Here are the logs with the new DLL. Still OOS turn 0.
[Logs-Client.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6697325/Logs-Client.zip)
[Logs-HOST.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6697327/Logs-HOST.zip)

**Comment by Toffer90** [comment]
> Here are the logs with the new DLL. Still OOS turn 0.

Thanks, still working on pinpointing it more precisely.

**Comment by Toffer90** [comment]
Another round. • [CvGameCoreDLL.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6697369/CvGameCoreDLL.zip)

Getting closer.

**Comment by Mouse** [comment]
Happy to help. Here's the next round of logs.

[Logs-Client.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6697446/Logs-Client.zip)
[Logs-HOST.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6697448/Logs-HOST.zip)

**Comment by Toffer90** [comment]
Thanks;
You guys go out of sync on this line:
GET_PLAYER(eNewPlayer).initInGame(eNewPlayer, bSetAlive);
For the first NPC initiated in the loop I mentioned

Of course that is another function with more lines to pinpoint within.
I have a feeling this function wasn't meant to be called before game is properly initialized, due to the name `"initInGame"`, this happens even before mapscript has started generating the map, so I wouldn't call that being in a game yet.

**Comment by Mouse** [comment]
That sounds like it could be a potentially critical bug.

**Comment by Toffer90** [comment]
Again: [CvGameCoreDLL.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6697573/CvGameCoreDLL.zip)

**Comment by Mouse** [comment]
There ya go.
[Logs-Client.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6697607/Logs-Client.zip)
[Logs-HOST.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6697609/Logs-HOST.zip)

**Comment by Toffer90** [comment]
Again: [CvGameCoreDLL.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6704640/CvGameCoreDLL.zip)

Still haven't tried to fix it, think I'll attempt to do so after this test.

**Comment by Toffer90** [comment]
Again: • [CvGameCoreDLL.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6704661/CvGameCoreDLL.zip)

Still no attempt to fix, I think I'll have enough info after this test to do so.

**Comment by Mouse** [comment]
And here ya go!
[Logs-Client.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6705102/Logs-Client.zip)
[Logs-HOST.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6705103/Logs-HOST.zip)

**Comment by Toffer90** [comment]
Does this fix the OOS? ♦ [CvGameCoreDLL.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/6711456/CvGameCoreDLL.zip)

If not, upload logs as usual.

**Comment by Mouse** [comment]
C2C_World_OOS_Test - Turn 10 Normal speed
C2C_Pangaea - Turn 10 Normal speed
C2C_World - Turn 10 Ultrafast

We built multiple units per turn, had all of them moving separately and automatically, built multiple gatherers and had them automate city improvement separately as well.

No OOS. Looking good.

**Comment by Toffer90** [comment]
Nice.

Thanks for sticking with the program helping us pinpoint this bug.
It was a quite recent OOS introduced when I figured out how to stop exe from allowing you to define more than 40 players in the staging room game setup screen. 
Slot 40-50 are reserved for NPC and stuff gets wonky if you in staging room assign a normal leader/civ to one of those slots.
