### ISSUE TITLE
Out of sync errors after starting a new game

### ISSUE THREAD

**Issue by alberts2** [caveman2cosmos/Caveman2Cosmos#104]
Right after starting a new multiplayer game it goes out of sync.
![oos](https://user-images.githubusercontent.com/6376945/64429312-f6377b80-d0b5-11e9-83ac-6c21c839d671.PNG)
The number of areas doesn't match
![areas](https://user-images.githubusercontent.com/6376945/64429612-aa390680-d0b6-11e9-99e3-0b378d0a15bc.PNG)
The starting units are on different plots.
![unit1](https://user-images.githubusercontent.com/6376945/64429613-aa390680-d0b6-11e9-8719-7f828bcd89ea.PNG)
![unit2](https://user-images.githubusercontent.com/6376945/64429614-aad19d00-d0b6-11e9-886e-049dd2dc5fbc.PNG)
Here are the oos logs
[Logs.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/3583999/Logs.zip)

**Comment by Toffer90** [comment]
Couple of factors we need to investigate here.

Does this happen with all map-scripts or just a few?
Starting position is strange, why aren't all those units on the same tile?
-- Was it advanced start?
-- World map-script place all the starting units of a player on the same tile always.
-- -- I know others don't, so this may be a good place to start looking into.

Is this with the culturally linked start option?

**Comment by billw2012** [comment]
I don't know this, however *surely* mapscript runs on host machine *then* syncs everything to the rest of the players, rather than running on every client separately and requiring all mapscripts to be deterministic? Surely they are infact non-deterministic by design!

**Comment by Toffer90** [comment]
All clients run their map-script independently, but they both should be using the same python seed in their map script and thus get a deterministic result.

This is from world map-script
`def PySeed():
	#Python randoms are not usable in network games.
	#AIAndy - I disagree. Python randoms are deterministic so the only important thing is to seed from a synchronized source like MapRand.
	if CyGame().isNetworkMultiPlayer():
		#AIAndy - seed Python random with MapRand
		GC = CyGlobalContext()
		mapRand = GC.getGame().getMapRand()
		seedValue = mapRand.get(65535, "Seeding mapRand - FairWeather.py")
		seed(seedValue)
		mc.seedString = "Random seed (Using getMapRand) for this map is %(s)20d" % {"s" :seedValue}
	else:
		#Python 'long' has unlimited precision, while the random generator
		#has 53 bits of precision, so I'm using a 53 bit integer to seed the map!
		seed() #Start with system time
		seedValue = randint(0, 9007199254740991)
		seed(seedValue)
		mc.seedString = "Random seed (Using Python rands) for this map is %(s)20d" % {"s" :seedValue}`

**Comment by Toffer90** [comment]
@billw2012: If you could manage to make the host send the map to the clients after map gen then that would be cool, although it would cause a delay in that sending the whole map data over possibly slow networks could take some time.

**Comment by alberts2** [comment]
The map script was Custom Continents and i can do more testing later.

**Comment by billw2012** [comment]
> It is actually quite rational to have each client generate the map on their own.

I don't see why. If people are running on 56k modems I would agree. In all other cases I think it makes more sense to generate it once and share the data (a few MB at most): it would mean everyone doesn't need to wait for the slowest computer (unless host is slowest, but that would be silly thing to do), and map scripts do not need to worry about being deterministic which would mean we wouldn't need to fix this bug.

**Comment by Toffer90** [comment]
I'm seeing some probable OOS causes in CvMapGeneratorUtil.py
It uses python random without seeding it first in `def generateTerrainAtPlot(self,iX,iY):`

All map-scripts except for PM, PW and World utilize that utility code for terrain generation.

**Comment by billw2012** [comment]
Its weird I didn't think anyone changed map gen code in months (I haven't see anyone mention it since I joined)

**Comment by Toffer90** [comment]
That's simply because OOS errors on game start has been an issue for years, and people don't play MP much because of the OOS issues.

**Comment by Toffer90** [comment]
> > It is actually quite rational to have each client generate the map on their own.
> 
> I don't see why. If people are running on 56k modems I would agree. In all other cases I think it makes more sense to generate it once and share the data (a few MB at most): it would mean everyone doesn't need to wait for the slowest computer (unless host is slowest, but that would be silly thing to do), and map scripts do not need to worry about being deterministic which would mean we wouldn't need to fix this bug.
>
I meant it was rational in 2007 (release of the game), and I'm also saying that changing it may be really hard as the exe controls a lot in the main-menu interaction code-flow, making it hard to change how it all works.

**Comment by alberts2** [comment]
Ok using the python function `random()` instead of the correct `getMapRand()` could defenitely explain the map generation causing out of sync errors.

**Comment by Toffer90** [comment]
getMapRand() is absolutely preferable over using a seeded python random in this case.

Question, maybe you know the answer, is there any real difference between 
`game.getMapRand().get(X, "blah")`
and `game.getSorenRandNum(X, "blah")`?

**Comment by alberts2** [comment]
> Question, maybe you know the answer, is there any real difference between
> `game.getMapRand().get(X, "blah")`
> and `game.getSorenRandNum(X, "blah")`?

Both work the same way it looks like `getMapRand` was added to have a separate random number generator for everything related to the map itself.

**Comment by Toffer90** [comment]
Huh, I find that a bit odd.

**Comment by alberts2** [comment]
The C2C World map script doesn't cause a out of sync error.

**Comment by Toffer90** [comment]
> The C2C World map script doesn't cause a out of sync error.
>
That's cool considering the world mapscript was the first code I ever wrote in my life.
(I had written some small autohotkey stuff before that though, but that doesn't really count.) ^^

**Comment by Toffer90** [comment]
Ok, I have a potential fix ready for this issue.

**Comment by Toffer90** [comment]
@alberts2: Could you check if [this commit](https://github.com/caveman2cosmos/Caveman2Cosmos/commit/2f3d5f438483b2d96996869ad342be0cc82990d9) fixed this OOS on new game issue.

**Comment by alberts2** [comment]
Looks good.
