### ISSUE TITLE
No space tornados please

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#105]
Filter by tile type or something? Volcano must be doing something like this, just copy that.

**Comment by raxo2222** [comment]
I'm not sure if this https://github.com/caveman2cosmos/Caveman2Cosmos/commit/f267b0600f5be767e66a7c3f8868b4471f20576a fixes issue with space tornadoes

**Comment by Toffer90** [comment]
> I'm not sure if this [f267b06](https://github.com/caveman2cosmos/Caveman2Cosmos/commit/f267b0600f5be767e66a7c3f8868b4471f20576a) fixes issue with space tornadoes
>
Maybe not as the event will still trigger on space terrain, would have to make the
`def canDoTornado(argsList):` check if the terrain is valid too.

You could also use the MapCategoryTypes tag on the tornado feature.

**Comment by raxo2222** [comment]
Volcano event doesn't have any filter in python

**Comment by Toffer90** [comment]
I'll add the terrain filter to the tornado canDo python code.

**Comment by raxo2222** [comment]
I think all feature/terrain/improvement/barbarian city isn't updated for space maps.
That is all those would need to be set to Earth map category.
I had bunkers spawning in space from Margot Line wonder.
Also in some other space save I saw space barbarians too - they don't care about map category just hills (this was where they spawned in space map).

**Comment by Toffer90** [comment]
Most python should ask the dll if this plot can have this feature, and the dll does in that query check the map category.

With your xml change and my python change I believe this issue can be considered closed.

**Comment by raxo2222** [comment]
> Most python should ask the dll if this plot can have this feature, and the dll does in that query check the map category.


Well not for space barbarians issue [Uploading Argalgane_April_4_AD-0752.zip…](here)
Also that one wonder spawning bunkers spawned them in space (borders of empire were in space).

**Comment by raxo2222** [comment]
>Most python should ask the dll if this plot can have this feature, and the dll does in that query check the map category.

Well not for space barbarians issue - it is same save where this issue was found https://github.com/caveman2cosmos/Caveman2Cosmos/issues/100.
Also that one wonder spawning bunkers spawned them in space (borders of empire were in space).

**Comment by Toffer90** [comment]
> > Most python should ask the dll if this plot can have this feature, and the dll does in that query check the map category.
> 
> Well not for space barbarians issue - it is same save where this issue was found #100.
> Also that one wonder spawning bunkers spawned them in space (borders of empire were in space).

I'll have a look at that bunker wonder issue.

**Comment by billw2012** [comment]
Fixed in f267b06
