### ISSUE TITLE
Out of sync errors after founding the first city

### ISSUE THREAD

**Issue by alberts2** [caveman2cosmos/Caveman2Cosmos#106]
![found](https://user-images.githubusercontent.com/6376945/64439844-28070d00-d0cb-11e9-90c5-dfd979cdd3d3.PNG)
Seems to be caused by the unit naming.
![unitnames](https://user-images.githubusercontent.com/6376945/64439863-32290b80-d0cb-11e9-81bd-2efeb511c330.PNG)

**Comment by Toffer90** [comment]
hmm, unit naming is just visual though, is there a way to not have the unit name be a part of the game state? Or is the unit name used for anything in other code relevant to game state?

**Comment by Toffer90** [comment]
I can probably fix it quite easily though, will look into it, I think it's mostly python code.

**Comment by Toffer90** [comment]
The problem with having the unit name as a game-state factor is that the naming convention is on a per player base stored in UserSettings as an ini file. So... Of course it's usually a good idea to use the exact same UserSetting folder whn playing MP...

Changing names manually and after training units in city probably creates a unit name OOS still, founding first city and getting units from goody huts is solved by not giving City name to the unit names in these cases.

**Comment by alberts2** [comment]
I wouldn't have a problem with removing that automatic unit naming because of the problems it causes or maybe at least it could be turned of by default.

It also might be a good idea to document all known options which cause issues in multiplayer games.

**Comment by Toffer90** [comment]
Yeah, this unitnaming system is all activated by a BUG option, so it wouldn't be too hard to force it off in multiplayer games.

**Comment by billw2012** [comment]
> It also might be a good idea to document all known options which cause issues in multiplayer games.
Definitely useful, ideally we can flag them all in code with this information and force them to MP safe values automatically (and add tooltip or whatever to indicate they won't work in MP so people don't report as bug).
Regarding unit auto naming, could it not just be a client side system only? i.e. Add another CvString and use that in all UI, but the "real" name stays the same. Probably this is a ton of work though, certainly just forcing the option off is the best short term solution I think!

**Comment by alberts2** [comment]
Founding a city still causes a out of sync error even with unit naming disabled.
But sadly the OOSLogger currently doesn't log the data which goes out of sync in this case.

**Comment by Toffer90** [comment]
That's odd, I will look into more city founding python code, maybe there's something easily spotted there.

**Comment by billw2012** [comment]
Its weird, I presume @Thunderbrd got further than founding a city before hitting OOS right?

**Comment by Toffer90** [comment]
> Founding a city still causes a out of sync error even with unit naming disabled.
> But sadly the OOSLogger currently doesn't log the data which goes out of sync in this case.

Were you using the game.option "No Revolution"?

**Comment by alberts2** [comment]
> Founding a city still causes a out of sync error even with unit naming disabled.
> But sadly the OOSLogger currently doesn't log the data which goes out of sync in this case.
> 
> Were you using the game.option "No Revolution"?

Yes

**Comment by Toffer90** [comment]
> > Were you using the game.option "No Revolution"?
> 
> Yes

Darn, I had a hunch that is no longer relevant due to that answer.

**Comment by Toffer90** [comment]
I'll see if I can't expand on the OOSLogger data output, there's probably more that it can easily output.

**Comment by alberts2** [comment]
It might be the production popup because it causes the random number generation to get out of sync.
![random](https://user-images.githubusercontent.com/6376945/64461082-77196600-d0fc-11e9-95b4-6cd8a7a8a6b7.PNG)

**Comment by billw2012** [comment]
Ah okay I will have a look then

**Comment by alberts2** [comment]
It was a easy fix so i did it myself.

**Comment by billw2012** [comment]
A nice thanks!!
