### ISSUE TITLE
Combat odds not always showing

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#112]
https://forums.civfanatics.com/threads/single-player-bugs-and-crashes-v39-plus-svn-after-the-20th-of-july-2019.647928/page-55#post-15538531

https://forums.civfanatics.com/threads/single-player-bugs-and-crashes-v39-plus-svn-after-the-20th-of-july-2019.647928/page-55#post-15539425

**Comment by dzfischer** [comment]
I personally have never seen combat odds fail to show when they should, _other_ than in the case where an isBlendIntoCity unit is attacking into a fort and kills a boat or plane, which leads me to suspect this is a problem with the canCoexist logic blocks somewhere. Can anyone confirm otherwise?

**Comment by Toffer90** [comment]
This does actually happen once in a while.
