### ISSUE TITLE
Improve assert system

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#113]
Add specific asserts for when modifier recalculation is probably required.
Add specific asserts for optional code paths, e.g. Size Matters. Perhaps just a general assert that takes an extra string parameter (use a macro though), or a specific `FAssertSizeMattersMsg()` macro for each option we want to add asserts for.

**Comment by Thunderbrd** [comment]
hmm... I'm open to seeing ways to improve on that.  Cool.

**Comment by billw2012** [comment]
Oh yeah I already did this is as well in a33e7dc9b77eba9a00071f6f614e791a6ae759d5, forgot to close the issue!
