### ISSUE TITLE
Fixing some misleading or redundant tech names

### ISSUE THREAD

**Issue by GreatCoffers** [caveman2cosmos/Caveman2Cosmos#117]
This one probably very minor, but I think this more or less will increase the immersion or at least inform players about the tech actually does.

I've typed up a google doc on what I renamed, as well as the associated eras.

It's here: https://docs.google.com/document/d/1hQeWf8sAG5_lbmsMNreaa9SlSVhhXwo-MuKW6yeb1ss/edit

**Comment by raxo2222** [comment]
Pepper renamed Exomining to Planet Cracking some time ago.

**Comment by billw2012** [comment]
`Medieval: Executions →  Capital Punishment`
Bit weird that this tech is medieval. Pretty sure humans have been executing and capitally punishing since way before 0AD.

**Comment by GreatCoffers** [comment]
raxo2222: I'm not sure why Pepper would that. Redundancy perhaps?

billw2012: I think the tech could at lest be place somewhere around the Middle Prehistoric, requiring Codes of Conduct. Torture also doesn't really make sense either as you have the Brazen Bull as building in Classical. Torture should be placed in or around the Prehistoric or Ancient era. For Prehistoric, it should at least require Slavery. For Ancient, I'm not sure.

**Comment by raxo2222** [comment]
Maybe he wanted original name?

As for crime/punishment techs @Thunderbrd designed them this way.

**Comment by GreatCoffers** [comment]
I'm not sure why he did that. It was likely for balance rather historical accuracy. Are there any other techs that may have some kind of problem or are worthy of discussion?

**Comment by Thunderbrd** [comment]
> Bit weird that this tech is medieval. Pretty sure humans have been executing and capitally punishing since way before 0AD.
Actually, this was Hydro.  With this and torture, we're not trying to say it wasn't happening beforehand, only that a new level of development was the focus of human endeavor during this age. 
 We were looking for ways to flesh out the era, give it more techs to soak up more research time, which was admittedly not an age of great accomplishments and was a fairly dark time, which we were also hoping to encapsulate some of that flavor.  I think he had some plans for that particular tech that didn't get fully completed and he might be worth asking about it in discord.
