### ISSUE TITLE
move PlotExtraYields from CvGame to CvPlot

### ISSUE THREAD

**Issue by MattOttawa** [caveman2cosmos/Caveman2Cosmos#1213]
There is already a comment from Toffer in the code:
// Toffer - ToDo - I think we want to use this more extensively,
//	so move it over to CvPlot and store extra yield in an array of three elements per plot.

Plot x, y is used to get and set values from a vector.
Multiple plots can have the same x, y if there are multiple maps.
What Toffer said would be good.

**Comment by MattOttawa** [comment]
I was gonna move CvGame::getPlotExtraCost to CvPlot, but the change function never seems to be called? should 
I add an int to CvPlot to that anyways?

**Comment by Toffer90** [comment]
Delete it, I can confirm that it is unused code, never called.
