### ISSUE TITLE
Missing Texts

### ISSUE THREAD

**Issue by alberts2** [caveman2cosmos/Caveman2Cosmos#123]
Lot's of unit class and building class descriptions are missing and after https://github.com/caveman2cosmos/Caveman2Cosmos/commit/6a8f2b8c6b97f3edbcaa8d73fbe29bb312f3d5ac they are all gone.

**Comment by raxo2222** [comment]
I guess these weren't corrected in class infos.
For example its TXT_KEY_BUILDING_BALLOON_RIDES and not TXT_KEY_BALLOON_RIDES as displayed in building infos.

**Comment by alberts2** [comment]
> TXT_KEY_CIV_HOLY_ROMAN_DESC exists in NamesCivs game text.

You are right about that one.

**Comment by raxo2222** [comment]
So you should exclude building/unit CLASS infos.
Also include all \*text\*.xml files

**Comment by alberts2** [comment]
> So you should exclude building/unit CLASS infos.

Why?

**Comment by raxo2222** [comment]
These are overridden by building/unit infos.

**Comment by raxo2222** [comment]
I removed all description tags from building/unit class infos, and building/unit names are displaying just fine

**Comment by alberts2** [comment]
They are not overridden why should they be?
At some places the building/unit class descriptions are actually displayed why would you remove them?

**Comment by raxo2222** [comment]
Because they needlessly cluttered bug report - I checked stuff in pedia, and there were no text errors here.

**Comment by alberts2** [comment]
Ok how would you explain code like `szString.append(gDLL->getText("TXT_KEY_UNIT_COMBAT_FLANKING_STRIKES", iFlank, GC.getUnitClassInfo((UnitClassTypes)iI).getDescription()));` here the unit class description is used.

That's not the only use of the unit class description and building class descriptions are displayed as well at multiple places!!!!!!!!!!!!!

**Comment by raxo2222** [comment]
Its in units game text.
[ICON_BULLET]%d1_Amount Strength [LINK=CONCEPT_FLANK_ATTACK]Flank attack[\LINK] against %s2_unitlist isn't unit description.

**Comment by alberts2** [comment]
`GC.getUnitClassInfo((UnitClassTypes)iI).getDescription()` returns the description of the unit class and not of the unit.

**Comment by raxo2222** [comment]
I did 100 turns on autorun, and didn't notice any TXT KEY errors in event log.

**Comment by alberts2** [comment]
I'am closing this now because @raxo2222 is saying that missing texts are actually not a bug.
