### ISSUE TITLE
Add callstack to asserts

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#125]
Will help with debugging of course.

For example: https://www.codeproject.com/Articles/11132/Walking-the-callstack-2

**Comment by Thunderbrd** [comment]
Cool.  I suppose this is to help give a better clue as to what you're looking at when you get the initial assert but you can still just hit debug to see the callstack whenever you get an assert if you're running through VS or attached to the process right?

**Comment by billw2012** [comment]
Yeah its so easy to add may as well do it. Its useful for when asserts get reported particularly, also with the number of asserts with no message whatsoever.

**Comment by Thunderbrd** [comment]
True those 'false' asserts alone are capable of driving one batty at times.

**Comment by billw2012** [comment]
Done already.
