### ISSUE TITLE
Missing UnitClass descriptions in unit help text

### ISSUE THREAD

**Issue by alberts2** [caveman2cosmos/Caveman2Cosmos#126]
Because all the UnitClass descriptions are empty after https://github.com/caveman2cosmos/Caveman2Cosmos/commit/6a8f2b8c6b97f3edbcaa8d73fbe29bb312f3d5ac a empty strings are now displayed in the unit help texts.
![missing text](https://user-images.githubusercontent.com/6376945/64484526-a53d9980-d213-11e9-93a5-24b07690d7fd.PNG)

E.g. FlankingStrikes look like this in the xml for the UNIT_CUIRASSIER:
![xml](https://user-images.githubusercontent.com/6376945/64484631-6c9ebf80-d215-11e9-9c02-3eeeec4159bf.PNG)

A problem of missing Building/Unit Class descriptions was discussed at https://github.com/caveman2cosmos/Caveman2Cosmos/issues/123 previously and the solution for missing texts was to just remove all descriptions.

**Comment by raxo2222** [comment]
So units use these after all. I'll restore all unit info descriptions.
Mismatched description tags between building class info and building info never were noticed.

**Comment by alberts2** [comment]
> So units use these after all.

Exactly like i said why didn't you belive me? The BuildingClass descriptions are used as well.

> Mismatched description tags between building class info and building info never were noticed.

It was noticed that's why i created #123 

> These class infos were meant to be removed by @Anq-civfanatics anyway.

Doesn't matter until it actually happens.
