### ISSUE TITLE
Missing BuildingClass descriptions.

### ISSUE THREAD

**Issue by alberts2** [caveman2cosmos/Caveman2Cosmos#127]
For  example building class info TXT_KEY_BALLOON_RIDES, and building info has TXT_KEY_BUILDING_BALLOON_RIDES, there was no text entry for former but exists for latter.

This means for that list of text errors one has to copy description tags from building infos to building class infos, as description tags in building class infos where outdated.

_Originally posted by @raxo2222 in https://github.com/caveman2cosmos/Caveman2Cosmos/issues/126#issuecomment-529176419_

**Comment by raxo2222** [comment]
I never saw this inconsistency in game, when it came to mismatched building class and building description tags.
This is why I thought all these description tags in unit/building class infos were just remains of some older system.

**Comment by alberts2** [comment]
The BuldingClass description is used in the dll six times for text display.
Here is a example of the BuildingClassProductionModifier from Civics.
`,if (kCivic.getBuildingClassProductionModifier(iI) != 0)
		{
			szFirstBuffer.Format(L"%s%c%d%s", NEWLINE, gDLL->getSymbolID(BULLET_CHAR), abs(kCivic.getBuildingClassProductionModifier(iI)), (kCivic.getBuildingClassProductionModifier(iI) > 0 ? gDLL->getText("TXT_KEY_CIVIC_BUILDING_CLASS_PRODUCTION_MOD") : gDLL->getText("TXT_KEY_CIVIC_BUILDING_CLASS_PRODUCTION_SLOW")).c_str());
			szBuilding.Format(L"<link=%s>%s</link>", CvWString(GC.getBuildingClassInfo((BuildingClassTypes)iI).getType()).GetCString(), GC.getBuildingClassInfo((BuildingClassTypes)iI).getDescription());
			setListHelp(szHelpText, szFirstBuffer, szBuilding, L", ", (kCivic.getBuildingClassProductionModifier(iI) != iLast));
			iLast = kCivic.getBuildingClassProductionModifier(iI);
			if (iLast == kCivic.getBuildingClassProductionModifier(iI))` 

I didn't check the python code for usages but at least the OOSLogger uses the Buldingclass description.

**Comment by raxo2222** [comment]
Now I wonder if it would be faster to tweak 20 GC.getBuildingClassInfo((BuildingClassTypes)iI).getDescription()) entries in CPP and get rid of description tag in building/unit class infos, or fix 200 mismatched description tags.

**Comment by billw2012** [comment]
Fixing the first is a simple search and replace, then we remove the `getDescription` function entirely from `BuildingClassInfo`, and the compiler will show us anywhere we missed.

**Comment by billw2012** [comment]
Maybe we can iteratively remove building classes in this manner in fact.

**Comment by alberts2** [comment]
> Now I wonder if it would be faster to tweak 20 GC.getBuildingClassInfo((BuildingClassTypes)iI).getDescription()) entries in CPP and get rid of description tag in building/unit class infos, or fix 200 mismatched description tags.
> Numbers are my guess :p

That would not be a simple tweak. Because these tags work with building classes and are called `BuildingClassProductionModifiers` you would have to complely rework them to `BuildingProductionModifiers`. That would require c++, xml and maybe python changes.

**Comment by raxo2222** [comment]
So fixing these by copying description tags from building/unit infos would be safer method.
But then again no TXT_KEY errors are reported.

**Comment by Thunderbrd** [comment]
Wouldn't be an issue if we could plan out the project to eliminate building classes and divide up the efforts between us and just dive in and get it done.  I know Anq was working on this but I had a feeling he'd end up giving up on his attempt in the way he was trying to go about it.  The tags need much more patient focus to convert over to building tags and not buildingclass tags.  I guess I feel any work on resolving this item would be a waste of time and overridden as soon as we really agree to focus in on evicting the building and unit class tags.

**Comment by billw2012** [comment]
Okay if that is something still planned then yeah we should focus on it instead.

**Comment by Thunderbrd** [comment]
Suppose we should make this an official project on the project list - I'll get to doing that as soon as I can but if you beat me to it I won't be upset ;)

**Comment by billw2012** [comment]
No I will leave it to you, when you create it choose "kanban with automation"

**Comment by Thunderbrd** [comment]
Well, I initiated it - it's asking for more to be done to flesh it out that I don't currently have time to do but I'll return to look at it more later.  I'll have to get some more information on what exactly 'kanban' means to begin with.  That's a new word for me.

**Comment by raxo2222** [comment]
All those descriptions tags in building and unit classinfos won't matter soon.
