### ISSUE TITLE
Get rid of separate tools submodule.

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#13]
@alberts2 
We have to have Tools for the project to build, it isn't shared or owned by someone else, so having a separate submodule just adds friction to all operations. e.g. Writing things that require changes to tools and code/makefile etc.

**Comment by alberts2** [comment]
I agree and aready changed it in https://github.com/caveman2cosmos/Caveman2Cosmos/commit/d489ec293152622aa71872b7891cb779b307292a.
