### ISSUE TITLE
Minor issues with Admin build tab

### ISSUE THREAD

**Issue by dzfischer** [caveman2cosmos/Caveman2Cosmos#1393]
All (as of writing) are minor and most are probably on Toffer's todo list somewhere, but listing here just in case:
- Recommended constructions doesn't suggest buildings
- Highlight of city is occasionally offset, uncertain circumstances causing it
![image](https://user-images.githubusercontent.com/47398228/185722172-d61b2ab2-3895-45c5-b471-6f679944e02a.png)
- Bar sticks around in worldbuilder if city is selected while ctrl-w is pressed. Replicates inconsistently.
![image](https://user-images.githubusercontent.com/47398228/185770138-db815d59-1fc5-47bc-896f-c3942cad93f5.png)

**Comment by dzfischer** [comment]
Feature requests also, I guess?
- Left-clicking an item should add it to the end of the queue if the identical item is currently on the top of the queue. E.g. if queue is currently "A, B, B", clicking C three times should result in the queue looking "C, B, B, C, C". Haven't tested this in an old svn ver, but it does exist in other civ4 mods to the point I feel it's a vanilla feature?
- "Go to city" bar should also be present on building, unit tabs (frequently find myself clicking them, then having to go back to admin tab to go to city)
- Main admin overlay could use some basic info about the city on the bottom left quadrant under recently produced items; some sort of condensed city screen with base hammer production, happiness, food stats, etc.

**Comment by flabbert** [comment]
many of these issues have been resolved, if some still persist open a new issue
