### ISSUE TITLE
C2C-GitVersion missing library?

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#14]
1>Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'LibGit2Sharp, Version=0.26.0.0, Culture=neutral, PublicKeyToken=7cbde695407f0333' or one of its dependencies. The system cannot find the file specified.
1>   at GitVersion.Program.Main()
1>NMAKE : fatal error U1077: '"..\\Tools\C2C-GitVersion.exe"' : return code '0xe0434352'

**Comment by alberts2** [comment]
Sorry for that and fixed in https://github.com/caveman2cosmos/Caveman2Cosmos/commit/c7a90bcf42f054c8f9af52e23375e2d754f73022.
