### ISSUE TITLE
Spies can't perform espionage against barbs; probably should be able to

### ISSUE THREAD

**Issue by dzfischer** [caveman2cosmos/Caveman2Cosmos#1431]
CvUnit::canEspionage contains a check for kTarget.isNPC() which barbs will fail.

Probably actions should be allowed, but will require some care to implement as barbs don't follow normal rules on many things.

**Comment by flabbert** [comment]
I could agree, but having a partial subset of espionage actions based on barbs only is probably pretty far outside of scope at the moment.
