### ISSUE TITLE
my units have dissapeared and ui broke 

### ISSUE THREAD

**Issue by xXSoulGamerXx** [caveman2cosmos/Caveman2Cosmos#1447]
reset my game and file 
still doesnt fix it even change opion setting thing that fix but nope 
im out ideas

![1](https://github.com/caveman2cosmos/Caveman2Cosmos/assets/91313507/b50f4069-dc35-4261-bcdc-a96136376ad4)
![2](https://github.com/caveman2cosmos/Caveman2Cosmos/assets/91313507/8fc4476d-c6ac-4073-ab70-ca3086cf7260)

**Comment by flabbert** [comment]
this looks like mod is installed in the wrong folder?

It needs to be installed in the game directory, and not in My Documents, also the mod folder name needs to be Caveman2Cosmos exactly

**Comment by m33n33** [comment]
I think you have the baremap option (Ctrl+E) turned on.

**Comment by flabbert** [comment]
closed due to lack of further response
