### ISSUE TITLE
Enhancement: Automate Hunt for animals only

### ISSUE THREAD

**Issue by paulcobbaut** [caveman2cosmos/Caveman2Cosmos#1525]
When assigning "Automate Hunt" to a chaser/hunter it (quickly) dies attacking a barbarian (stack or even city).

![automate_hunt](https://github.com/user-attachments/assets/c2a1a749-6203-4828-9286-fc2fe1ecc698)

It would be nice to have an automate hunt feature that only targets animals and runs away from barbarians. Definitely when the hunter is far away from home I don't care about the barbarians and would prefer they annoy the other players instead of killing my hunter.

Apologies if this exists in the latest version.

**Comment by flabbert** [comment]
which version of the game are you playing on? downloaded from moddb or SVN version?

**Comment by paulcobbaut** [comment]
The latest 'stable' from moddb.

**Comment by flabbert** [comment]
then I would suggest you try with SVN version, SVN is now considered more stable than the moddb version, because we are able to fix bugs there a lot faster than the proper release.

https://github.com/caveman2cosmos/Caveman2Cosmos/wiki/Using-SVN

**Comment by paulcobbaut** [comment]
Thanks, I tried svn three weeks ago and it crashed immediately, could not start a game.

Will try again when this game is finished (maybe in six months...).

Closing the issue.

**Comment by flabbert** [comment]
yes, we broke saves between latest moddb release and current svn, so playing svn now means starting new game
