### ISSUE TITLE
Galley Can't load a settler

### ISSUE THREAD

**Issue by Thunderbrd** [caveman2cosmos/Caveman2Cosmos#177]
https://forums.civfanatics.com/threads/single-player-bugs-and-crashes-v39-plus-svn-after-the-20th-of-july-2019.647928/page-76#post-15560831

I downloaded the save but have to look at why this is not working properly.  Just glancing at the promos on the ship I don't think it should be having trouble.

**Comment by flabbert** [comment]
pretty sure this works now? can you confirm @Thunderbrd
