### ISSUE TITLE
Building OR pre-reqs aren't listed in wiki

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#192]
https://forums.civfanatics.com/threads/caveman-2-cosmos-ideas-discussions-thread.377892/page-951#post-15570992

**Comment by Toffer90** [comment]
I'll look into this.

**Comment by MattOttawa** [comment]
Can this be closed?

**Comment by alberts2** [comment]
Are these missing OR pre-reqs defined inside the ConstructCondition tag?

**Comment by raxo2222** [comment]
> Are these missing OR pre-reqs defined inside the ConstructCondition tag?

You got that backward:
There is building X, which is OR requirement for building  Y
Pedia won't display that building X can unlock building Y.

**Comment by raxo2222** [comment]
Fix would be:
If you are on BUILDING X page, then search all buildings with line <PrereqOrBuilding>
If some building has 
`<PrereqOrBuilding>
					<BuildingType>BUILDING_X</BuildingType>
					<bPrereqBuilding>1</bPrereqBuilding>
				</PrereqOrBuilding>`
then add it to pedia entry of building X.

Searching for <ConstructCondition> would be similiar
`
<ConstructCondition>
				<Or>
					<Has>
						<GOMType>GOM_BUILDING</GOMType>
						<ID>BUILDING_X</ID>
					</Has>
					<Has>
						<GOMType>GOM_BUILDING</GOMType>
						<ID>BUILDING_Y</ID>
					</Has>
				</Or>
			</ConstructCondition>
`

**Comment by raxo2222** [comment]
Fix would be:
If you are on BUILDING X page, then search all buildings with line \<PrereqOrBuilding>
If some building has 
\<PrereqOrBuilding>
					\<BuildingType>BUILDING_X\</BuildingType>
					\<bPrereqBuilding>1\</bPrereqBuilding>
				\</PrereqOrBuilding>
then add it to pedia entry of building X.

Searching for \<ConstructCondition> would be similiar

\<ConstructCondition>
				\<Or>
					\<Has>
						\<GOMType>GOM_BUILDING\</GOMType>
						\<ID>BUILDING_X\</ID>
					\</Has>
					\<Has>
						\<GOMType>GOM_BUILDING\</GOMType>
						\<ID>BUILDING_Y\</ID>
					\</Has>
				\</Or>
			\</ConstructCondition>

**Comment by raxo2222** [comment]
It appears it was surprisingly easy to fix.

https://github.com/caveman2cosmos/Caveman2Cosmos/commit/bae1861f4530faf5b984a5308f62a1416973c085
