### ISSUE TITLE
Raw vicinity requiring buildings aren't listed on resource entries in wiki unlike normal vicinity requiring buildings

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#193]
https://forums.civfanatics.com/threads/caveman-2-cosmos-ideas-discussions-thread.377892/page-951#post-15571021

> Also GOM requirement type of resource isn't listed on that resource page.

> So for example unit requires ammunition defined by GOM tag, then ammunition resource page won't display, that this unit requires it.

**Comment by raxo2222** [comment]
Partially done - GOM dtuff needs to be exposed to python
https://github.com/caveman2cosmos/Caveman2Cosmos/pull/1014

**Comment by raxo2222** [comment]
This is done now.
https://github.com/caveman2cosmos/Caveman2Cosmos/commit/67c1bb8c9d6e1d02cfd6afcb49f9517f610474fc
