### ISSUE TITLE
See Invisible AI is massively overtraining units for the need

### ISSUE THREAD

**Issue by Thunderbrd** [caveman2cosmos/Caveman2Cosmos#197]
This is my best guess as to why there are a huge number of dogs being trained for attack and defense forces.  Somewhere it is failing to understand that it has enough where it needs it.  It's possible it could be a slightly different issue, as in if Dog units are being evaluated as the best UnitAI Attack unit, which would be a very different bug with the same results we've had reported.

**Comment by billw2012** [comment]
This appears fixed (in tested cases so far) by 804d5395741c2fb992d2ef03ffd07cde0f18aacf.
