### ISSUE TITLE
Implement version generation using git-describe 

### ISSUE THREAD

**Issue by alberts2** [caveman2cosmos/Caveman2Cosmos#2]

**Comment by alberts2** [comment]
@billw2012 
Something like [https://stackoverflow.com/a/8358264](https://stackoverflow.com/a/8358264) could work for us.

**Comment by billw2012** [comment]
Yeah I did exactly this in my previous project

**Comment by billw2012** [comment]
This works now right?

**Comment by alberts2** [comment]
One thing that's left to do is to not overwriting the version.cpp if it already has the same content as the new file would have.

**Comment by alberts2** [comment]
The commit https://github.com/caveman2cosmos/C2C-GitVersion/commit/680833edffe6085303280564bf031b4b07da5d8c contains the change to not overwrite the version.cpp if it already exists and contains the same code as the new file would.

**Comment by alberts2** [comment]
> One thing that's left to do is not overwriting the version.cpp if it already has the same content as the new file would have.
Done in https://github.com/caveman2cosmos/Caveman2Cosmos/commit/7eb4fc17ed982911dd8e0dd3474faef11885783e
