### ISSUE TITLE
Add AppVeyor artifacts for the Assert/FinalRelease dlls that we can pull for devs in install/update scripts.

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#21]
Not sure if we can pull AppVeyor artifacts directly or if we need to make GitHub releases out of them. 
I'm concerned some people aren't going to be happy about building the DLL themselves!

**Comment by billw2012** [comment]
https://www.appveyor.com/docs/api/samples/download-artifacts-ps/
This can be adapted to download the latest dll artifacts. Need to make sure we add a local token for the last downloaded artifact so we don't download it again.
For some people building might be faster than download, allow them to choose.

**Comment by flabbert** [comment]
has this been done? it feels like a good thing to have, if not, is it something we can trick you to do bill? :)

**Comment by OvermindDL1** [comment]
You can always automate the build system to post the compiled artifacts as a github release, easier with github actions rather than appveyor but still doable there if you do the post request yourself.
