### ISSUE TITLE
Check "Tradition - Hunting" is possible to build.

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#224]
Can't see how it is, it doesn't appear to be referenced anywhere.

**Comment by raxo2222** [comment]
This one has -1 cost, so is placed in special buildings section.
No unit can build it unlike Tradition - Hunter or something like that.
Tradition - Hunter gives free building, that is upgrade of Tradition - Hunting free building.
Dancing Houskuld left it hanging

**Comment by billw2012** [comment]
So what is the solution? Remove it?

**Comment by raxo2222** [comment]
You can remove it

**Comment by billw2012** [comment]
#234 addresses this.
