### ISSUE TITLE
Make sure, that you can't have more 39 civs on game start (by selecting them), and that you can't assign them to team number bigger than 39.

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#230]
https://forums.civfanatics.com/threads/cant-attack-anything.650934/

**Comment by raxo2222** [comment]
In those saves "stay by hand" status is missing and NPCs are treated like players

**Comment by raxo2222** [comment]
It appears players were tampering with game files (reduced amount of civs to 40, then reverted to 50 civs), or they downloaded wonky scenarios.

**Comment by raxo2222** [comment]
It appears player was forcing NPCs to be one team.
You can technically force NPCs to other slots or teams by editing scenario files.
You can simply make NPCs belong to one team on game start
