### ISSUE TITLE
City production tooltip calculation is wrong.

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#232]
It applies modifiers to overflow.
Probably overflow should NOT include modifiers, as currently it will incorrectly apply modifiers specific to the whatever was built *last* turn to the overflow you can use *this* turn.
Apply modified hammers to current build, then separately apply non-build specific modifiers and calculate over flow from that, *then* reverse the modifiers on the overflow amount.

**Comment by flabbert** [comment]
Is this done?
