### ISSUE TITLE
Deleting "Band of Homo-sapiens" in WB will stop Tribal Guardian spawning

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#237]
Might be worth looking into why, as maybe it indicates some underlying problem, or weird impl.

**Comment by dzfischer** [comment]
Fixed as of current version; "Ancestral Band" units start with free promo to spawn tribal guardians, works independently of killing unit with WB. I think Toffer made this change, somewhat recently.

**Comment by Toffer90** [comment]
> Fixed as of current version; "Ancestral Band" units start with free promo to spawn tribal guardians, works independently of killing unit with WB. I think Toffer made this change, somewhat recently.

I did, I was also cheeky enough to give the promo to both the AI starting settlers on deity/nightmare diff. This causes some asserts though as the AI get two tribal guardians which are national units with a limit of 1. Thinking I should remove the limit on them as they can't be trained in cities anyhow can they?

**Comment by dzfischer** [comment]
Yeah, if they can't be trained, no reason to have limit.
