### ISSUE TITLE
Some plots flipping culture periodically

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#241]
Save here:
https://forums.civfanatics.com/threads/single-player-bugs-and-crashes-v40-plus-svn-after-oct-2019.650924/page-6#post-15594212

**Comment by flabbert** [comment]
I dont know if this is still valid

**Comment by Toffer90** [comment]
It is, something is weird with culture decay/growth, perhaps only when using realistic culture option.

**Comment by dzfischer** [comment]
Decisively stopped by just removing the rule
https://github.com/caveman2cosmos/Caveman2Cosmos/commit/c657bdd8152ac5cd9caaba2fc810129fffb66d94
