### ISSUE TITLE
End of turn forces full memory usage.

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#243]
During EOT it appears that all entities are forcibly paged in? Memory usage appears to go to what one would expect with paging disabled.
Weirdly memory usage will drop again in most cases back to paging specification.
Entering tech tree view somehow causes memory to be freed, but can also cause crash?

**Comment by raxo2222** [comment]
Memory usage seems to slowly increase trough hours of AI autorun, and then it gets much lower if you exit game

**Comment by flabbert** [comment]
@billw2012 @raxo2222 has this been triaged?
