### ISSUE TITLE
`CvUnit::getCargoCapacitybyType` has dead codepath in it

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#244]
It is disabled now, maybe an error in there. 
Certainly there is room for generalizing some of the math that appears to be going on here.

**Comment by Thunderbrd** [comment]
Please reenable.  Upon review this is working as planned and the impression of irrationality is understandable.  Some notes may have helped.  I commented in Discord further.  Some of this is the fact that there is a preparation for getting information from an XML tag that does not yet exist and so is instead hardcoded for now and the limited options of modification here are not as widely varied as the system is intended to accommodate for the potential for eventually.

**Comment by Thunderbrd** [comment]
Once you understand the setup based on my feedback in discord, if you feel there's a better way to write these formulas, I'm very willing to consider improvements.  I did the best I knew how to do with my level of understanding here.

**Comment by billw2012** [comment]
This was fixed by extracting and generalizing the rank scaling method.
