### ISSUE TITLE
Find method for per frame updates

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#261]
d3d9.dll wrapper time?
Currently game update is called ever 250ms or so, which makes paging choppy and UI interactions that rely on it unresponsive.

**Comment by MattOttawa** [comment]
CvDLLEngineIFaceBase has:
	virtual float GetUpdateRate() = 0;
	virtual bool SetUpdateRate(float fUpdateRate) = 0;
