### ISSUE TITLE
Replace C style arrays with managed collections of some kind.

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#284]
Might be `boost::array`, `std::vector` (or better alternative), or `boost::scoped_array` (as last resort).

**Comment by OvermindDL1** [comment]
`std::vector` is probably the best in any case, if an array is being reallocated often (they only reallocate when increased beyond their capacity) then there's another issue somewhere anyway.

**Comment by billw2012** [comment]
> std::vector is probably the best in any case
There are lots of places I want stack allocation where boost::array will be better, and also many places where something like [this](https://youtu.be/vElZc6zSIXM?t=320) (small vector optimization) would be ideal! And scoped_array helps where an interface returns an already allocated pointer to the data and we need to take over ownership. I'm not certain if that happens anywhere we can't change yet, but it is my backup plan!

**Comment by OvermindDL1** [comment]
Ah you mean the small stack optimization, where something is on the stack until it's too large and 'overflows' onto heap allocation, yeah that can be quite useful, there are some good libraries for that though I can't recall it's name off hand...  Boost had a small vector library I thought, specific for those use cases...

**Comment by billw2012** [comment]
> Boost had a small vector library I thought
We are limited to 1.32 boost as the exe is tied to boost python version. I would guess it will be somewhat of a nightmare to try and use another version for parts of the library. However thinking about it now, perhaps boost allows setting the namespace name override explicitly so we could keep them separate...

**Comment by OvermindDL1** [comment]
Actually boost is *very* segmented.  The Boost Python version you may be limited to a specific version but you aren't for the rest.  And using tools like `bcp` (part of boost) you can actually pull out a library or libraries out of boost, entirely segmented into a new namespace and all, you can mix and match as you wish.  ^.^

**Comment by billw2012** [comment]
Ah yes very helpful. I swear last time I looked at bcp it wasn't considered usable (I don't remember the details, just remember getting the impression it didn't work).

**Comment by OvermindDL1** [comment]
It's a bit of a pain to set up but it's worked well for me in the past, plus you only have to do it once per pull (or can even do it manually).

**Comment by billw2012** [comment]
What I really need to do is write something that will automate this for me, seems like it should be possible...
Or at least find all instances and let me choose for each one/per class.
Some kind of more general code-modernization refactoring tools would be useful, where it can automate everything that only has one solution, and then let me choose between solutions where there are more than one.

**Comment by OvermindDL1** [comment]
Heh, well I've never come across one that can do this specific task, but it is technically not at all hard to build one with libclang (though would be a bit of code), unsure if it is worth the work though.  ^.^;
