### ISSUE TITLE
Planes selected as fort defenders against criminals

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#286]
https://forums.civfanatics.com/threads/single-player-bugs-and-crashes-v40-plus-svn-after-oct-2019.650924/page-11#post-15606026

**Comment by dzfischer** [comment]
Naval units may also selected as defenders

**Comment by dzfischer** [comment]
Issue still in game, not related to taunt chance; is some issue with coexist rule block and isBlendIntoCity()

**Comment by dzfischer** [comment]
Duplicate and/or subset of #112
