### ISSUE TITLE
Automated units return to a city when ready to upgrade.

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#287]
But they don't wake upon getting to the city so player is unaware.

**Comment by billw2012** [comment]
Maybe have global setting to toggle returning for upgrade, or just get rid of the behaviour for human units.

**Comment by Toffer90** [comment]
They shouldn't return at all on auto hunt, they shouldn't assume the player can afford their upgrade cost right away.
