### ISSUE TITLE
Add git to dependencies! 

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#29]
Needed to run FPKLive + other tools so we better make sure everyone has it installed!

**Comment by billw2012** [comment]
https://git-scm.com/download/win

**Comment by alberts2** [comment]
It would be possible to use libgit2sharp https://github.com/caveman2cosmos/FPKLive/issues/2. 
But we could also add git itself.

**Comment by billw2012** [comment]
I added a download and install step to the DevSetup.bat script if a git command line install can't be found.
