### ISSUE TITLE
Move C2C version entirely out of DLL

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#291]
i.e. replace C2C_VERSION macro with loading from a file. 
Currently ~~EXE~~ DLL is rebuilt every time always because version changes with every CI build.

**Comment by Toffer90** [comment]
What do you mean by "the exe is rebuilt"?
Do you mean dll?

**Comment by billw2012** [comment]
Yeah I meant dll

**Comment by flabbert** [comment]
was this done?
