### ISSUE TITLE
Automatic custom game settings for scenarios.

### ISSUE THREAD

**Issue by raxo2222** [caveman2cosmos/Caveman2Cosmos#314]
Currently your game options choice is preserved when you generate new maps.
It remembers your settings as they are in vanilla BTS ini file in C:\Users\<USERNAME>\Documents\My Games\Beyond the Sword\CivilizationIV.ini

But for scenarios it is different: those are set as defined in scenario files.
This means someone has to spend time setting up game options (for example turning off Revolutions or turning on Upscaled research costs) when wanting to play a scenario.

Is it possible to add button in game setup screen (where you pick various options when you select scenarios) to load your settings choice from INI file overriding scenario settings?

**Comment by Toffer90** [comment]
Custom scenario already exist.
We can't modify the UI of the main menu as all of it is handled by the exe. Only thing we can do is tweak the UI style slightly through the thm files.

**Comment by raxo2222** [comment]
I know, that custom scenario exists.

So it is possible to add keyboard shortcut that changes scenario selection to players selection of game settings?

**Comment by raxo2222** [comment]
Another problem with scenarios is that they can options turned off/on, while they should be turned on/off, for example assimilation, ecological animals, usable mountains and more.

That is some scenarios may have assimilation or usable mountains OFF, while they are hidden and ON by default, so you can't turn them on in scenarios.

**Comment by raxo2222** [comment]
I deleted all options from scenarios, so this is unnecessary now.
