### ISSUE TITLE
Fassert inconsistency

### ISSUE THREAD

**Issue by MattOttawa** [caveman2cosmos/Caveman2Cosmos#326]
Matt: The line that follows the FAssert can't pass without triggering the FAssert.

void CvTeam::changeAliveCount(int iChange)
{
	m_iAliveCount += iChange;
	FAssert(getAliveCount() >= 0);

	// free vassals
	if (0 == m_iAliveCount)
	{
		for (int iTeam = 0; iTeam < MAX_TEAMS; iTeam++)
		{
			if (iTeam != getID())
			{
				CvTeam& kLoopTeam = GET_TEAM((TeamTypes)iTeam);
				if (kLoopTeam.isAlive() && kLoopTeam.isVassal(getID()))
				{
					kLoopTeam.setVassal(getID(), false, false);
				}
			}
		}
	}
}

**Comment by billw2012** [comment]
Why? `m_iAliveCount == 0` satisfies `m_iAliveCount >= 0`.

**Comment by Toffer90** [comment]
I think matt has assert logic upside down.
The assert triggers if m_iAliveCount < 0.
So the line that follows FAssert can't pass if the FAssert was triggered.

**Comment by MattOttawa** [comment]
too much pot
