### ISSUE TITLE
Using SVN Instructions

### ISSUE THREAD

**Issue by WilsonCA** [caveman2cosmos/Caveman2Cosmos#328]
Anyone needing these instructions will not be familiar with SVN. The Program Files directory tree won't have full control permission by default for any user, even the admin. Including a brief instruction to change the properties permission, if receiving an "Access is Denied" error, might be helpful. Something like the following screenshots:
![image](https://user-images.githubusercontent.com/20366072/71644899-08a97680-2c9e-11ea-9779-66a18b8af3f1.png)
![image](https://user-images.githubusercontent.com/20366072/71644923-532af300-2c9e-11ea-9427-f6c1b497bb1b.png)
Or just linking to someone's blog. This page showed up in a Google search: https://hellowahab.wordpress.com/2012/03/16/cant-create-directory-svn-access-is-denied/

**Comment by dzfischer** [comment]
Updated SVN install guide
