### ISSUE TITLE
Many tool tips are offset in windowed mode

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#33]
I promised @Toffer90 to add a DLL function for getting proper mouse position for tool tips.

**Comment by billw2012** [comment]
So I can't see any obvious place to put general user interface code, so I guess I will put this in the GlobalContext directly as something like `getMousePos()`?

**Comment by Toffer90** [comment]
Global context would be most appropriate imo.

**Comment by billw2012** [comment]
@Toffer90  I fixed up the Python side to use my new functions (I saw that wx does have functions that should allow this, but I guess they are removed in the Civ version of those libs?).
Anyway if it is good then accept the PR #61

**Comment by Toffer90** [comment]
Yeah, tried getting it from wx, but without knowing the memory addresses of the exe instances of the different wx objects related to the game window.... there's really no way to ask those instances where the game window is from our python code.

**Comment by billw2012** [comment]
Well _misc exposes global function `GetActiveWindow()` and the object it returns exposes `ScreenToClient()` in the unmodified version of wxPython. I tried these and it didn't work though. I didn't investigate far, as I was told Civ libs are modified anyway. Probably they remove all direct Window functions from wx to stop modders from doing funky things?

**Comment by Toffer90** [comment]
_misc.GetActiveWindow always return None when I called it.

**Comment by Toffer90** [comment]
So a missing library is also the case

**Comment by billw2012** [comment]
Adding new functions to GC is trivial by the way, so if you have more requests put in a github issue for them and I can put them in in one go

**Comment by Toffer90** [comment]
I looked at the python change in the branch and tested it in game, lookes good to go for a merge to master. I'll do a more systematic adjustment to the python side of that after the merge.
