### ISSUE TITLE
Have a look at dxvk, see if it can give us any benefits.

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#331]
https://github.com/doitsujin/dxvk/tree/v1.5

**Comment by OvermindDL1** [comment]
I don't see how?  Not unless you are wanting to wrap it all up into a wine build, but even then Civ4's DX version is so old that dxvk wouldn't even be used (it's for DX10+), and rather wine's normal DX->OGL mapping would be used (and works perfectly as that's how I run it).

**Comment by raxo2222** [comment]
Well someone said that it can be used for old games on Windows https://forums.civfanatics.com/threads/caveman-2-cosmos-ideas-discussions-thread.377892/reply?quote=15627600

**Comment by raxo2222** [comment]
Someone said it can be used for old games on Windows too https://forums.civfanatics.com/threads/caveman-2-cosmos-ideas-discussions-thread.377892/page-965#post-15627600

**Comment by OvermindDL1** [comment]
That's [d9vk](https://github.com/Joshua-Ashton/d9vk), which is a different project, it translates DirectX9 calls to vulkan calls.  It will not help with any 4gig limitation as that's a limitation of being a 32-bit application, what it's referencing with `Implemented the ability to use more than 4GB VRAM on 32-bit applications` is only for VRAM, not RAM.  Civ4/C2C is not anywhere near needing that much VRAM (plus 'most' GPU's still don't even have that much unless you have extremely new and modern GPU's).  In addition it's not designed to be built into an application, it's built on Wine's API's.

**Comment by OvermindDL1** [comment]
What would really be nice is if someone at Firaxis could get them to release the Civ4 source, then we could make the changes necessary to make it a full and proper 64-bit application.  Until that then just rewriting it would be the only way to release this memory limitation.

**Comment by raxo2222** [comment]
Ah so someone misunderstood what this thing does.

**Comment by billw2012** [comment]
Yeah I don't know anything about it really, someone mentioned we should look at it so I added this as a reminder.
