### ISSUE TITLE
Barbarian tech should not be highest of existing civs

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#35]
Perhaps lowest, average, one era behind?

**Comment by ViriatoLusitano** [comment]
I'd go with lowest.

**Comment by Thunderbrd** [comment]
Lowest could be a problem if you get that one crippled AI that never goes anywhere and then suddenly barbs know a few eras more of techs once it dies and before that they are artificially held back to complete cavemen.  Perhaps average would be better.

**Comment by Toffer90** [comment]
Barbs are rarely doing well technologically in my games...
I would like to actually see saves from normal games showing this to be a real problem.

**Comment by Thunderbrd** [comment]
It may also be a complaint coming from the pirate events that spawn the NEXT era's ships that NO civ yet has access to.
