### ISSUE TITLE
Tree nursery and similar aren't working

### ISSUE THREAD

**Issue by raxo2222** [caveman2cosmos/Caveman2Cosmos#353]
Those improvements are meant to plant forest or other features.

Reported on Discord bug thread.

**Comment by MattOttawa** [comment]
I remember this from playing. I wouldn't mind fixin for myself.

**Comment by Thunderbrd** [comment]
There are new tags for placing features and I'm not sure if they've ever been tested properly.  Look into that - it may just be that the builds need to implement the new tags correctly is all.

**Comment by MattOttawa** [comment]
I just took a quick look.
There's a tag for CvBuildInfo but nothing for CvImprovementInfo.
If I remember correctly, after building the first improvement you get the young forrest (CvBuildInfo).
When the improvement upgrades you don't get new feature (should be tag on CvImprovementInfo).
Maybe.

**Comment by Toffer90** [comment]
The tree nursery has to be worked by a city for X amount of turns before it upgrades to the young forest improvement.
The young forest imp has the tag:
```xml
<FeatureChangeTypes>
	<FeatureType>FEATURE_FOREST_NEW</FeatureType>
</FeatureChangeTypes>
```
Is it the FeatureChangeTypes that is not working correctly, that the young forest improvement appear but no new forest?

**Comment by Toffer90** [comment]
I'm not convinced that the improvement isn't working correctly, it could work better or differently, but I don't think there's a bug here.

**Comment by Toffer90** [comment]
There is some odd semi-conflicting python code in CvEventMangaer.onImprovementBuilt().

There's probably been some conflict of idea on how to implement it, which was further muddled when the young forest feature was added to C2C, which was after the "tree nursery", "young forest", and "plant forest" improvements were already in the game.

I'm thinking we should ditch the "tree nursery" and "young forest" improvements, and only keep the "plant forest" improvement.
I don't know if it would be best to use the onImprovementBuilt python event to plant a young forest feature whenever a worker has built a "plant forest" improvement. Or to utilize the dll coded improvement tag called <FeatureChangeTypes> instead of python.

**Comment by Thunderbrd** [comment]
I agree.  Look... guys... it should not be necessary for a build to result in an improvement.  It should, in this case, result in a feature instead.  Expecting the city to work a terrible plot just to grow it into a forest is maybe workable for human players if they go out of the way to force it to work at a sacrifice to the productivity of that population which would be better spent on almost any other specialist instead.  The AI flat out won't do it without writing in some kind of incentive to that doesn't currently exist.  DH suspected there was something wrong on the py side there as well.  I completely agree that it should just be plant a forest.  Then we can eliminate young forest entirely from the assets unless we really want it for a forest growth/age/fire cycle mod.

**Comment by Toffer90** [comment]
> a forest growth/age/fire cycle mod.

This is implemented in python in MToS btw.
It is quite random, so perhaps we want workers to be able to do a build called grow forest that requires the plot to already have a "new forest" feature, and when the build finish the new forest is replaced by a regular forest, I think ancient forests should not be possible for a worker to build, it needs to come naturally from the randomized forest aging python script similar to what I've done in MToS.

**Comment by Thunderbrd** [comment]
Why are you bogarding this in your own MTOS mod?  I believe we identified that as a great mod concept for the main a long time ago.  If we need to, we could implement it as an option at least.  I agree completely with your staging.  A worker build could place the new forest, then place the forest over a new forest.  Makes sense to me.

**Comment by Toffer90** [comment]
> Why are you bogarding this in your own MTOS mod?

A couple of reasons.
It was experimental, not every idea should be thrown into C2C either.
I hadn't decided if it was a good idea myself yet, and I kinda forgot about it.

**Comment by Toffer90** [comment]
Fixed in forestBuildAging branch that I just merged to master.
