### ISSUE TITLE
Rephrase the tooltip on Dynamic XP

### ISSUE THREAD

**Issue by Thunderbrd** [caveman2cosmos/Caveman2Cosmos#381]
Reword the dynamic so that it doesn't suggest that only on dynamic you'd get more reward for higher risk than you would on the core.

Something like "no lower limit on xp gain", or "no minimum xp from combat", in the description.

**Comment by dzfischer** [comment]
Solved by this commit:
https://github.com/caveman2cosmos/Caveman2Cosmos/commit/bf5f866eabc4c18934421e0b62e77a5888e90ac9
