### ISSUE TITLE
Assert CvPlayer::getSpecialistExtraCommerce(eIndex) >= 0

### ISSUE THREAD

**Issue by MattOttawa** [caveman2cosmos/Caveman2Cosmos#390]
ASSERT FAILED
==============================================================================================================================================================================
File:        C:\Users\uhm\Documents\GitHub\Caveman2Cosmos\Sources\CvPlayer.cpp
Line:        17587
Expression:  getSpecialistExtraCommerce(eIndex) >= 0
==============================================================================================================================================================================
DLL CALLSTACK:
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
sources\cvplayer.cpp (17587): CvPlayer::changeSpecialistExtraCommerce
sources\cvplayer.cpp (35031): CvPlayer::processTrait
sources\cvplayer.cpp (1979): CvPlayer::addTraitBonuses
sources\cvplayer.cpp (35235): CvPlayer::recalculateModifiers
sources\cvteam.cpp (9765): CvTeam::recalculateModifiers
sources\cvgame.cpp (13699): CvGame::recalculateModifiers
sources\cvmessagedata.cpp (1388): CvNetRecalculateModifiers::Execute
004F8DEE (Civ4BeyondSword): (filename not available): (function-name not available)
CA8868FF (module-name not available): (filename not available): (function-name not available)

**Comment by Thunderbrd** [comment]
Specialists should now be allowed to cause negative extra commerce (to COST the city.)  This would be a result of the newer trait set assuming this is legal which the original vanilla intent was that it wouldn't be.  The main thing to check before disabling this assert forever would be to ensure that it actually is displaying and calculating correctly when that happens.  I would think I did that but another set of eyes on it would be appreciated.

**Comment by Toffer90** [comment]
I'll test it by trying to set some high negative commerce for early game specialist to test the extreme cases of loosing more from specialist than what one is gaining from any all other income sources.

**Comment by MattOttawa** [comment]
Should I delete the FAssert and close this? Nothin wrong with a FAssert goin obsolete if you guys know what's goin on.
