### ISSUE TITLE
Assert CvPlot::getVisibilityCount(eTeam) >= 0

### ISSUE THREAD

**Issue by MattOttawa** [caveman2cosmos/Caveman2Cosmos#391]
ASSERT FAILED
==============================================================================================================================================================================
File:        C:\Users\uhm\Documents\GitHub\Caveman2Cosmos\Sources\CvPlot.cpp
Line:        10734
Expression:  getVisibilityCount(eTeam) >= 0
==============================================================================================================================================================================
DLL CALLSTACK:
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
sources\cvplot.cpp (10734): CvPlot::changeVisibilityCount
sources\cvplot.cpp (2452): CvPlot::changeAdjacentSight
sources\cvplot.cpp (2719): CvPlot::updateSight
sources\cvmap.cpp (480): CvMap::updateSight
sources\cvteam.cpp (4267): CvTeam::changeExtraWaterSeeFromCount
sources\cvteam.cpp (7334): CvTeam::processTech
sources\cvteam.cpp (9774): CvTeam::recalculateModifiers
sources\cvgame.cpp (13699): CvGame::recalculateModifiers
sources\cvmessagedata.cpp (1388): CvNetRecalculateModifiers::Execute
004F8DEE (Civ4BeyondSword): (filename not available): (function-name not available)
CA8868FF (module-name not available): (filename not available): (function-name not available)

**Comment by Thunderbrd** [comment]
I'm not sure how this is going right now so it would be up for open evaluation and I can't say much to this currently.
