### ISSUE TITLE
Error in windowActivation event handler when alt+tab

### ISSUE THREAD

**Issue by marcin-derlukiewicz** [caveman2cosmos/Caveman2Cosmos#399]
i play in windowed mode, when i change active window to game, error appears in log.

![screen](https://user-images.githubusercontent.com/6348155/72749336-0d38bf00-3bba-11ea-8834-7b0ccc1b72de.png)

using # v40.0.1185 - 2020-01-15 REV:11105

**Comment by raxo2222** [comment]
Don't use github version if you are just playing.
I never got this error, upload your save, user settings and BTS INI file.

**Comment by billw2012** [comment]
Well, if using SVN just use SVN update only of course. FYI I always play windowed, don't see this error.

**Comment by Toffer90** [comment]
My guess is that something is wrong with your Caveman2Cosmos Config.ini

Compare yours to this:
[Caveman2Cosmos Config.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/4091625/Caveman2Cosmos.Config.zip)

**Comment by marcin-derlukiewicz** [comment]
i use svn, and i use update
[Logs.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/4105302/Logs.zip)

[marci February 11, BC-0389.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/4105295/marci.February.11.BC-0389.zip)

[Caveman2Cosmos.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/4105285/Caveman2Cosmos.zip)

**Comment by Toffer90** [comment]
To get the logs needed you will have to turn on python logging in your ini file.
Documents\My Games\Beyond the Sword\CivilizationIV.ini
loggingenabled = 1

The interesting log in this case is PythonErr.log and it will only be written to if the above ini setting is true.

Though, try running the game as an admin, it might clear out that problem your'e having.

**Comment by marcin-derlukiewicz** [comment]
[PythonErr.log](https://github.com/caveman2cosmos/Caveman2Cosmos/files/4149258/PythonErr.log)

**Comment by raxo2222** [comment]
Try switching to English language

**Comment by marcin-derlukiewicz** [comment]
I play in english and with admin permissions

**Comment by raxo2222** [comment]
Delete INI files and base mod folder and then revert them
You can try deleting User Settings folder

**Comment by Toffer90** [comment]
[Caveman2Cosmos Config.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/4149379/Caveman2Cosmos.Config.zip)
Try using this file instead of what you currently have in Beyond the Sword\Mods\Caveman2Cosmos

**Comment by marcin-derlukiewicz** [comment]
@Toffer90 you sent one file only and it is same as mine

**Comment by raxo2222** [comment]
Are you using steam? Then this may be helpful. https://forums.civfanatics.com/threads/for-those-who-use-steam-to-play-c2c.639734/

**Comment by Toffer90** [comment]
> @Toffer90 you sent one file only and it is same as mine

That is strange as the python error log is saying it can't read it.
NoSectionError: No section: 'Enhanced Tech Conquest'

It doesn't find this [Enhanced Tech Conquest] at the top of the file, or perhaps it isn't finding the file at all.

**Comment by Toffer90** [comment]
Could you upload your pythonDbg.log file too?

**Comment by raxo2222** [comment]
Why CvEnhancedTechConquestEventManager does even contain this section?
```
	def onWindowActivation(self, argsList):
		bActive = argsList[0]
		if bActive:
			EnhancedTechConquest.loadConfigurationData()
```

**Comment by Toffer90** [comment]
> Why CvEnhancedTechConquestEventManager does even contain this section?

So that you can alt tab out and change the settings, and when you alt tab in again the settings will be loaded right away.

**Comment by marcin-derlukiewicz** [comment]
[PythonDbg.log](https://github.com/caveman2cosmos/Caveman2Cosmos/files/4149478/PythonDbg.log)

**Comment by raxo2222** [comment]
Does other things in mod do even act like this?
He should check if he doesn't have mod folder within mod folder for example Caveman2Cosmos/Caveman2Cosmos

Or mod may be too deep in directory tree

**Comment by Toffer90** [comment]
> Does other things in mod do even act like this?
> He should check if he doesn't have mod folder within mod folder for example Caveman2Cosmos/Caveman2Cosmos

Not the case as his UserSettingsfolder is here ↓, so it seems ok
E:\SteamLibrary\steamapps\common\Sid Meier's Civilization IV Beyond the Sword\Beyond the Sword\Mods\Caveman2Cosmos\UserSettings

**Comment by marcin-derlukiewicz** [comment]
there is something that looks like hint at line 1094 of pythonDbg

**Comment by Toffer90** [comment]
There is something odd with your installation though, as the error happens in this file:
"e:/main/civilization4/warlords/assets/python/system\ConfigParser.py"

**Comment by raxo2222** [comment]
@marcin-derlukiewicz use beta version of game https://forums.civfanatics.com/threads/for-those-who-use-steam-to-play-c2c.639734/

This may be cause of error

**Comment by raxo2222** [comment]
> 
> 
> there is something that looks like hint at line 1094 of pythonDbg

Sounds like somehow you have outdated init.xml in config folder - do cleanup of it.
Or delete entire config folder and then revert it.

**Comment by Toffer90** [comment]
> there is something that looks like hint at line 1094 of pythonDbg

That is actually the same error as in error log, only that it is the error that is happening when initializing the game, not when switching window focus.

**Comment by raxo2222** [comment]
> 
> 
> > there is something that looks like hint at line 1094 of pythonDbg
> 
> That is actually the same error as in error log, only that it is the error that is happening when initializing the game, not when switching window focus.
> 
> > Sounds like somehow you have outdated init.xml in config folder - do cleanup of it.
> 
> There is probably no error in his init.xml file, that error shows that init is doing what is supposed to do,, the error is still in trying to read that config.ini file.

I guess he should go nuclear and install game in shorter patch, and reinstalling mod from scratch including deleting user settings folder....

**Comment by Toffer90** [comment]
Perhaps he should delete 
C:\Users\marci\OneDrive\Documents\My Games\Beyond the Sword\CivilizationIV.ini
While he's at it. It will be recreated when you next start BtS.

**Comment by raxo2222** [comment]
This probably was user error
