### ISSUE TITLE
No write access to master

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#4]
@alberts2  Perhaps this is intentional, but I have no write access to master, I can't accept a PR to it.

**Comment by alberts2** [comment]
That's intentional the master and release branches are protected at the Moment. You can't push to them directly and pull requests require one review before they can be merged.

**Comment by alberts2** [comment]
I just looked and that rule actually applies to everyone including people in the admin role.

**Comment by billw2012** [comment]
What did you think about doing development in master once we are ready to switch to git? I think it will make the transition that much easier (people don't need to immediately switch to another branch once they join). We can use another branch in place of master for our "stable" build or whatever.

**Comment by alberts2** [comment]
The release branch could be for releases including preview or beta versions and the master branch would be for development.

But at least bigger or disruptive changes like save breaking changes should go through feature branches. That would keep the master branch more stable and would still allow multiple modders to work as a team on bigger projects or long taking developments in separate branches.

**Comment by billw2012** [comment]
> But at least bigger or disruptive changes like save breaking changes should go through feature branches.
Yeah definitely.

**Comment by billw2012** [comment]
master is merged and ready for use, locks released
