### ISSUE TITLE
Assert about global defines not being int

### ISSUE THREAD

**Issue by MattOttawa** [caveman2cosmos/Caveman2Cosmos#402]
I'm 90% sure it's talkin about the bool ones.
I been using my branches, so I've been waiting for someone else to report.
Is anyone else gettin these asserts?

**Comment by raxo2222** [comment]
Most likely it was caused by your conversion of ints

**Comment by MattOttawa** [comment]
That is not in mod or any of branches I was using.
If somebody builds a debug dll at some point plz let me know if you get asserts.

**Comment by raxo2222** [comment]
I built assert DLL, and didn't get this error.

**Comment by raxo2222** [comment]
There are your commits in your main fork, that aren't in main repository

**Comment by MattOttawa** [comment]
Thanks but i wrote this kinda wrong.
I was actually using debug dll and it wasn't typical assert.

**Comment by Toffer90** [comment]
Nope, I'm not getting a single error on the debug dll even after starting a new game and playing three turns in.

Something is likely wrong with your xml's or perhaps your setup in general.
