### ISSUE TITLE
Add tools to manage art/audio/text linkage (example: unused files, unused ART/AUDIO/TEXT tags, broken references)

### ISSUE THREAD

**Issue by raxo2222** [caveman2cosmos/Caveman2Cosmos#418]
There may be unused art/audio files - no references to files in mod.
Unused art/audio/text defines - files (TXT_KEY being defined but not used by anything) being referenced, but no actual ingame use.
Items that reference sound/art/text entries, but those entries may be not existing or files not existing.

This tool should consider vanilla files when backtracking to source (thing may be not defined/existing in mod, but be located/defined in vanilla).

TEXT:
Text (TXT_KEY) is defined in text xml files.
`Example: TXT_KEY_BUILDING_ANIMAL_MYTH_REQUIRE is defined in Animals_CIV4GameText and used by zAnimals_CIV4Building(Class)Infos xml.`

ART:
Art (ART_DEF) is defined in artdefines xml files.
They also contain file path entries.
`Example: ART_DEF_BONUS_BARLEY is defined in CIV4ArtDefines_Bonus and used by CIV4BonusInfos.xml
It also references couple files.
<NIF>Art/Terrain/Resources/Barley/Wheat.nif</NIF>
<KFM>Art/Terrain/Resources/Barley/Wheat.kfm</KFM>
<Button>,Art/blank.dds,Art/Interface/Buttons/AtlasMapBonus.dds,1,6</Button>`

AUDIO:
Audio (no consistent tag) are defined in Audio folder.
Sound scripts are used in variety of places, and they use sound defines which then point to files.
`Example:
Some buildings use scriptID AS2D_BUILD_STABLE, which references soundID SND_BUILD_STABLE, which uses <Filename>Sounds/Buildings/Stable</Filename>`

**Comment by billw2012** [comment]
Well we can't verify vanilla files on CI of course, so that would be optional depending on where you run it (unless we just build a database of all valid vanilla values to include).

**Comment by raxo2222** [comment]
It could be simply tool in Tools folder, so you can check if you didn't remove that TXT KEY by accident or if you used art used somewhere else.
First it could search within mod, and then within vanilla assets.

**Comment by raxo2222** [comment]
Seems like I reported it twice...
