### ISSUE TITLE
Great Wall code in CvCity is disabled due to bugs

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#44]
> TBNote: I've found both a crash scenario in PBEM and an infinite hang scenario in single player.
> A player complained about exceedingly strange graphic artifice when they encircle the globe with a singular culture that possesses the GW and the hang looked to have a similar basis.
> Unfortunately, I'm no front end specialist and I don't have a theory on how to isolate the cause except to say that it's the new way that the GW is being processed that's causing the crashes and hangs.
> So for now, this is disabled.  I may eventually create a manual option to turn it off or on and that would give us the ability to turn it off only if it's creating problems.
> Better would be to FIX it but I've got no clue on that.
@Thunderbrd

**Comment by Toffer90** [comment]
Is this something new, or an issue that has probably been around a long time?

**Comment by billw2012** [comment]
No idea just found it in the CPP comments while doing some code cleanup

**Comment by Thunderbrd** [comment]
Something to do with what happens when the wall has the ability to span the globe, it goes wonky.  The regular recalculating it was doing was also causing a major stutter problem.

**Comment by MattOttawa** [comment]
As an attempt to move this issue in the right direction, I'd like to enable the code again and also add #ifdef INCLUDE_THE_GREAT_WALL around all the code. My goal is to give others the ability to turn it on/off in a somewhat simple way for testing in the future.
Sound good?

**Comment by billw2012** [comment]
You could do, I [added a section in CvGameCoreDLL.h for "feature flags"](https://github.com/caveman2cosmos/Caveman2Cosmos/blob/46264f7f4da7cf6c2c1c3c2bd3ac0154f6d257f9/Sources/CvGameCoreDLL.h#L117) so you can add this flag there, with an explanation and a link to this issue, then comment it out.

**Comment by MattOttawa** [comment]
I'll need to get the xml back in the game.
If the team wants The Great Wall wonder back in without the extra wall feature I'll try disabling just the tag that enables it. If the team doesn't want The Great Wall in the game without the extra feature I'll make a function to delete the buldingInfo for release builds.
Or sumthin.

**Comment by Thunderbrd** [comment]
Isn't the Great Wall already still in the game?  It was only the graphic effect on the map that was disabled IIRC.

**Comment by raxo2222** [comment]
Wonder is here, just graphic effect was disabled.

**Comment by MattOttawa** [comment]
oh oops

**Comment by MattOttawa** [comment]
that makes things a bit simpler.
