### ISSUE TITLE
fix Bonus text XML file -- duplicates and wrong entries

### ISSUE THREAD

**Issue by SannitaSSJ** [caveman2cosmos/Caveman2Cosmos#445]
There are two minor fixes to put in stage asap:
* TXT_KEY_BONUS_GHANIAN is a non-functioning duplicate of TXT_KEY_BONUS_GHANAIAN and should be removed
* TXT_KEY_BONUS_GOLD_OREEN_HORDE should be renamed back into TXT_KEY_BONUS_GOLDEN_HORDE

Thanks.

**Comment by raxo2222** [comment]
Both of these are now fixed
