### ISSUE TITLE
CvPlayerAI::AI_captureUnit always returns true

### ISSUE THREAD

**Issue by MattOttawa** [caveman2cosmos/Caveman2Cosmos#471]
The following line is the only spot it is called. The whole line is currently pointless.

if (GET_PLAYER(eCapturingPlayer).isHuman() || GET_PLAYER(eCapturingPlayer).AI_captureUnit(eCaptureUnitType, pPlot) || 
0 == GC.getDefineINT("AI_CAN_DISBAND_UNITS"))

**Comment by alberts2** [comment]
The 'CvPlayerAI::AI_captureUnit' function seems to be no longer needed. Because  the AI was changed to always capture Units.

You can remove that function if you want to do it.
