### ISSUE TITLE
Write an XML tool for more user friendly editing of the XMLs

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#49]
Some possible features:

-  query/filter options
-  mass edit of a set of objects of the same class
-  clone existing object
-  reference navigation through related objects
-  perform script based modification (e.g. run on a property `value = value * 0.5`)

**Comment by flabbert** [comment]
notepad++ solves this for now, its a good idea, but better overall planning of structure with regards to infos needs to be undertaken first (TB's reviews)
