### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by alberts2** [caveman2cosmos/Caveman2Cosmos#498]
Compiling the `master` branch produces some c++ compiler warnings!

`Building Debug-build ...
11
1> Run: C:\projects\caveman2cosmos\Build\Debug\CvGameCoreDLL.res
12
2> Obj: C:\projects\caveman2cosmos\Build\Debug\CvGameCoreDLL.pch
13
1> Uni: Sources-Unity
14
2> WARNING: C:\projects\caveman2cosmos\Build\Debug\CvGameCoreDLL.pch
15
CvGameCoreDLL.cpp
16
c:\projects\caveman2cosmos\Sources\GlobalDefines.h(89) : warning C4010: single-line comment contains line-continuation character
17
c:\projects\caveman2cosmos\Sources\GlobalDefines.h(90) : warning C4010: single-line comment contains line-continuation character
18
c:\projects\caveman2cosmos\Sources\GlobalDefines.h(91) : warning C4010: single-line comment contains line-continuation character
19
c:\projects\caveman2cosmos\Sources\GlobalDefines.h(92) : warning C4010: single-line comment contains line-continuation character
20
c:\projects\caveman2cosmos\Sources\GlobalDefines.h(93) : warning C4010: single-line comment contains line-continuation character
21
c:\projects\caveman2cosmos\Sources\GlobalDefines.h(94) : warning C4010: single-line comment contains line-continuation character
22
c:\projects\caveman2cosmos\Sources\GlobalDefines.h(95) : warning C4010: single-line comment contains line-continuation character
23
c:\projects\caveman2cosmos\Sources\GlobalDefines.h(96) : warning C4010: single-line comment contains line-continuation character
24
c:\projects\caveman2cosmos\Sources\GlobalDefines.h(97) : warning C4010: single-line comment contains line-continuation character
25
c:\projects\caveman2cosmos\Sources\GlobalDefines.h(98) : warning C4010: single-line comment contains line-continuation character
26
c:\projects\caveman2cosmos\Sources\GlobalDefines.h(99) : warning C4010: single-line comment contains line-continuation character
27
c:\projects\caveman2cosmos\Sources\GlobalDefines.h(100) : warning C4010: single-line comment contains line-continuation character
28
c:\projects\caveman2cosmos\Sources\GlobalDefines.h(101) : warning C4010: single-line comment contains line-continuation character
29
c:\projects\caveman2cosmos\Sources\GlobalDefines.h(102) : warning C4010: single-line comment contains line-continuation character
30
c:\projects\caveman2cosmos\Sources\GlobalDefines.h(103) : warning C4010: single-line comment contains line-continuation character
31
c:\projects\caveman2cosmos\Sources\GlobalDefines.h(104) : warning C4010: single-line comment contains line-continuation character
32
c:\projects\caveman2cosmos\Sources\GlobalDefines.h(105) : warning C4010: single-line comment contains line-continuation character
33
c:\projects\caveman2cosmos\Sources\GlobalDefines.h(106) : warning C4010: single-line comment contains line-continuation character
34
2> Obj: C:\projects\caveman2cosmos\Build\Debug\CvGameTextMgr.obj`

[Complete log](https://ci.appveyor.com/project/Caveman2Cosmos/caveman2cosmos/builds/31776439)

**Comment by MattOttawa** [comment]
gimme second
my bad

**Comment by alberts2** [comment]
@MattOttawa 

You can close issues by using keywords like 'closes #498' in the commit message https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue
