### ISSUE TITLE
Fix or remove scenarios with missing resources.

### ISSUE THREAD

**Issue by raxo2222** [caveman2cosmos/Caveman2Cosmos#506]
Space maps could get their earth portion regenerated, and earth scenarios could be removed or fixed.

GUINEA_PIGS - StrategyOnly's Land_Testing C2C_Narnia 17 st 69X59
SEA_LION_AND_SEAL - A Space Map - Duel World, Desert Planet Fixed
WALRUS - Desert Planet Fixed, StrategyOnly's Land_Testing C2C_Narnia 17 st 69X59,  A Space Map - Duel World
MANGANESE - All maps except A Space Map - _Snofru_*

If those maps below weren't fixed, then I suggest fixing their resources or removing them
Desert Planet fixed - BEAVERS, HYDROTHERMAL_VENT, MAMMOTH, METHANE_ICE, NATRON, SEA_LION_AND_SEAL, WALRUS
psGiant Earth Map - 5 civs 12513 - GUAVAS, NATRON, PARROTS, TURQUOISE
StrategyOnly's Land_Testing C2C_Narnia 17 st 69X59 - DIAMOND, GEOTHERMAL_ENERGY, GUAVAS, HENNA, INDIGO, JADE, KAVA, METHANE_ICE, NATRON, NATURAL_GAS, PAPYRUS, PARROTS, RUBBER, TURQUOISE, WALRUS
StrategyOnly - ELEPHANTS, GEODE, GEOTHERMAL_ENERGY, GUAVAS, GUINEA_PIGS, HYDROTHERMAL_VENT, KAVA, LEMONS, MAMMOTH, METHANE_ICE, NATRON, NATURAL_GAS, PARROTS, PEARLS, RICE, SALT, WHALE

**Comment by raxo2222** [comment]
I think its important to fix missing resources on scenarios.

**Comment by flabbert** [comment]
has there been made any attempt at fixing these maps? i vaguely remember a discussion about it

**Comment by raxo2222** [comment]
I set non-spacemaps to randomly generate resources on scenario start.

So now non-snofru spacemaps may be missing Walrus, Sea Lion and Manganese - not very critical resources.
So I can close it.
