### ISSUE TITLE
Inaccurate AI power calculations

### ISSUE THREAD

**Issue by WilsonCA** [caveman2cosmos/Caveman2Cosmos#510]
The power (or "Soldier") values displayed by the game in the Demographics screen, the Power Graph, and on the score board, are not matching. At least one (up to all three?) must be inaccurate. The player and the AI both use this information in making war (and many other diplomatic interactions). This might only be a bug in display, and if so it is a minor annoyance for the player, but might also explain some idiosyncrasies in AI behavior if the inaccurate values are being used by the engine to determine military strategy. Concerned that it is happening in the first place, but also or where (just display to human, or deeper in the AI strategy decisions) the inaccuracy is first occurring.

**Comment by WilsonCA** [comment]
An example explanation of what the power/soldier values mean, and how they are calculated, can be found at https://www.civfanatics.com/civ4/strategy/game-mechanics/the-inner-workings-of-the-demographics-screen-explained/. This article does not go in to how this information is used by the AI or by the player, but little imagination is required to take the leap to application, once the values/graphs are well understood.

**Comment by WilsonCA** [comment]
Looks like Greatest Works are also confused, though I _think_ those are really just displayed for human flavor. 
![image](https://user-images.githubusercontent.com/20366072/78236840-8dc44780-74a8-11ea-9162-62664a35703c.png)
![image](https://user-images.githubusercontent.com/20366072/78236941-af253380-74a8-11ea-872b-3a65d4d879fd.png)

**Comment by Toffer90** [comment]
The Top civ "powerful" ranking just use the total accumulated iPower value of the civs.

**Comment by WilsonCA** [comment]
Yep. As does the Soldiers line in the Demographics screen. 2 <> 15.

**Comment by raxo2222** [comment]
Units, techs, buildings have ipower

**Comment by Toffer90** [comment]
Nope, the soldiers line only looks at power value from units, while the top civ looks at units+techs+buildings+etc

**Comment by WilsonCA** [comment]
So, this was an intentional change from vanilla civ4? If so, that solves some of the problem

**Comment by Toffer90** [comment]
> So, this was an intentional change from vanilla civ4?

Don't know, not familiar to how any of this was in vanilla, or if it's been changed in C2C at some point.

**Comment by Thunderbrd** [comment]
As for iPower, I will be smoothing that over in the unit planning project I'm in now.  It's a lower priority goal than some of the ones I've been addressing first here but it's a unit tag so it will be reviewed on all land units and was addressed in the Naval planning, though would probably be re-reviewed again there after this review.
