### ISSUE TITLE
Combat Classes of Subdued Animals

### ISSUE THREAD

**Issue by WilsonCA** [caveman2cosmos/Caveman2Cosmos#513]
The combat classes of subdued animals give them abilities that might be unintended. For example, the camouflage visibility of the below subdued fox. Should subdued units have the characteristics of the subdued (caged?) animal, or of the captors?
![image](https://user-images.githubusercontent.com/20366072/78237728-b4cf4900-74a9-11ea-98e6-e009aaa76190.png)

**Comment by Toffer90** [comment]
Fixed in 501e25182f2284e689beb45918b74e9a84a45422
