### ISSUE TITLE
bForceOverwrite (possible issue only with PrereqOrBuildings) in buildinginfos tag is broken

### ISSUE THREAD

**Issue by raxo2222** [caveman2cosmos/Caveman2Cosmos#516]
Building in module doesn't have PrereqOrBuildings unlike in core, and it is leaking to module override. This affects more buildings, not just BUILDING_ORBITAL_FACTORY
![Civ4BeyondSword 2020-04-03 16-29-51-23](https://user-images.githubusercontent.com/54320715/78371985-fa366800-75c8-11ea-8c1a-709d47c64acf.png)

**Comment by raxo2222** [comment]
I removed it in things outside of modules.
Currently all buildings in My_Mods\Bead_Toy_Pottery module rely on it
Ascension Gate and some Cislunar buildings depend on it in Pepper module.

**Comment by Toffer90** [comment]
Just to clarify: so the modules tries to remove the PrereqOrBuildings from core; but that fails?

**Comment by raxo2222** [comment]
Yes

**Comment by raxo2222** [comment]
<PrereqInCityBuildings> is correctly removed - compare <Type>BUILDING_ORBITAL_FACTORY</Type> in module and in core.
<PrereqOrBuildings> seems to be only one not working, also it is double-nested tag (PrereqIn... is single-nested)

**Comment by raxo2222** [comment]
Its fixed now https://github.com/caveman2cosmos/Caveman2Cosmos/pull/519
