### ISSUE TITLE
Using the bForceOverwrite tag on Buildings wastes alot of memory.

### ISSUE THREAD

**Issue by alberts2** [caveman2cosmos/Caveman2Cosmos#570]
Using the `bForceOverwrite` tag on Buildings initiates arrays like `m_piPrereqNumOfBuilding` in `CvBuildingInfo::copyNonDefaultsReadPass2` even if they should not. These arrays should only be initiated if the building needs them e.g. in case of the  `m_piPrereqNumOfBuilding` array the `PrereqAmountBuildings` tag has to be used in the xml.
https://github.com/caveman2cosmos/Caveman2Cosmos/blob/60edaea271ab638220e7297bd3e20858aa45dc8c/Sources/CvBuildingInfo.cpp#L6844-L6859
https://github.com/caveman2cosmos/Caveman2Cosmos/blob/60edaea271ab638220e7297bd3e20858aa45dc8c/Sources/CvBuildingInfo.cpp#L6885-L6932

**Comment by Thunderbrd** [comment]
Great catch!  Are you considering attempting a solution other than just a warning that it should be used as limited as possible?  I try to avoid its use anyhow but not do.

**Comment by raxo2222** [comment]
Currently its used on 32 module buildings. Units doesn't have this tag.

**Comment by alberts2** [comment]
> Great catch! Are you considering attempting a solution other than just a warning that it should be used as limited as possible? I try to avoid its use anyhow but not many others do.



> Great catch! Are you considering attempting a solution other than just a warning that it should be used as limited as possible? I try to avoid its use anyhow but not many others do.

I'am slowly catching up with all the changes made in the last months and didn't have time to fix this instantly. This issue was introduced by the BuildingClass and UnitClass removal so maybe the modders who worked on that want to take a look at this first.

**Comment by Toffer90** [comment]
I think both me and Matt would appreciate it if someone with a greater understanding of that replacement system would fix this caching issue that we created unwittingly when removing those classes.

**Comment by Toffer90** [comment]
lol I hate that the close and comment is so close to the comment button.

**Comment by MattOttawa** [comment]
if ((bOver || getBuildingHappinessChanges(j) == iDefault) && pClassInfo->getBuildingHappinessChanges(j) != iDefault)

Something like that?
