### ISSUE TITLE
Recalculate modifiers does not process replaced buildings correctly for cities

### ISSUE THREAD

**Issue by Toffer90** [caveman2cosmos/Caveman2Cosmos#616]
City recalc is doing something wrong, and I'm quite sure it has to do with replaced buildings in the building recalc.
This save is a new game on latest svn (rev 11201), played with autoplay for enough turn to get trade routes in cities, recalc has never been performed on that save.
It does not throw asserts when entering the city or mousing over the city defense to get that tooltip. but if you do a recalc on this save, you will get lots of asserts for trade routes and the city defense tooltip, values not being what they should be.
[BeforeRecalc.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/4967987/BeforeRecalc.zip)

**Comment by Toffer90** [comment]
The bug can be reproduced reliably with this save that was started on rev 11201 and never been performed recalc on.
[BeforeRecalc.zip](https://github.com/caveman2cosmos/Caveman2Cosmos/files/4967984/BeforeRecalc.zip)

**Comment by flabbert** [comment]
according to toffer this has been fixed
