### ISSUE TITLE
Verify that the correct dll is used at runtime

### ISSUE THREAD

**Issue by alberts2** [caveman2cosmos/Caveman2Cosmos#62]
We need something to make sure that people don't forget to recompile the dll.
That might be necessary after they switch to another branch or pull changes from our github repo.

**Comment by billw2012** [comment]
Yeah we can get git sha from Sources dir, and match it against DLL version sha, and show big red text on screen if they don't match.
I am considering how to automate this entirely. One thing I am looking into is making CvCoreGameDLL.dll a shim that just checks if the actual DLL needs building, then builds it and loads it, and forwards all function calls to it directly. I won't do it that way unless it is easy to do (automate the interface generation), has negligible performance impact, and is stable. Of course the release version would just use the normal DLL directly. 
I'm not sure I will look into doing that unless we run into problems with people forgetting to rebuild the DLL frequently though.

**Comment by billw2012** [comment]
I will add a popup dialog during DLL attach if the DLL isn't up to date. Maybe with a button to build it and restart the game.

**Comment by raxo2222** [comment]
You could add multichoice option if you can - that is build final release DLL and wait 15 minutes, or just release DLL.

**Comment by billw2012** [comment]
Fixed in 2382877536e1669972dd024ce2d0f3d0d5ffd988
