### ISSUE TITLE
C2C_World mapscript can generate lake tiles directly touching saltwater tiles in rare circumstances

### ISSUE THREAD

**Issue by dzfischer** [caveman2cosmos/Caveman2Cosmos#660]
When a lake center spawns touching [another lake], and then grows to the ocean, the code that checks to create a harbor and convert to ocean type doesn't include the lake tiles from [another lake].

Rare issue.

![Earthlike_Standard_RandEccen_Scale1_ERROR](https://user-images.githubusercontent.com/47398228/94111331-e8b07900-fe11-11ea-844a-086bcc3154c9.png)

**Comment by Toffer90** [comment]
interesting.

**Comment by flabbert** [comment]
This is actually something that is possble in real life isnt it? if the lake is a little bit higher altitude than sealevel, the lake will be freshwater and a large "river" feeds to the ocean

**Comment by dzfischer** [comment]
Estuaries are a thing, true. However, it doesn't look that great imo as the textures currently are, and would definitely require changes to the mapgen in order to make it sensible to reality. 

In this particular case it was due to a bug in lake spawning logic in the c2c_world mapscript, which I forgot to mark closed with the most recent push that fixed it.
