### ISSUE TITLE
Re-add all wonder movies.

### ISSUE THREAD

**Issue by Toffer90** [caveman2cosmos/Caveman2Cosmos#67]
Notes:
-Still images should be .dds instead of .bik.
-The python code that triggers these movies for buildings will need look at the path ending to see if it's a .bik or a .dds, as they cannot be displayed with the same code, new code is needed for displaying a simple dds image instead of a movie.
-The correct <MovieDefineTag>ART_DEF_MOVIE_X</MovieDefineTag> then needs to be added back to all the wonders and other misc stuff that triggered movies.

**Comment by alberts2** [comment]
Or maybe use static dds images everywhere instead of movies.

**Comment by billw2012** [comment]
Invalid is when the bug itself is invalid, unless you saying your own bug report isn't valid!

**Comment by Toffer90** [comment]
lol, Description of the "Invalid" tag was "Something isn't right" which I found quite accurate about the sudden lack of wonder movies. ^^

**Comment by billw2012** [comment]
I think this cuts across everything, if we need new code, new xml tag, new art. Only python that isn't needed here right?

**Comment by Toffer90** [comment]
Overkill much. ^^

**Comment by billw2012** [comment]
most tags ever reward for this issue

**Comment by alberts2** [comment]
> lol, Description of the "Invalid" tag was "This doesn't seem right" which I found quite accurate about the sudden lack of wonder movies. ^^

I'am not sure why this would be a huge problem because lots of wonders never had any kind of movie anyways.

**Comment by Toffer90** [comment]
Well, even the 80% that were only a still picture still had a list of the wonder stats popping up on top of the image; and graying out the image a bit for readability when it appeared.
I think players like the wonder completed feature where the camera zooms in on the city, and a panel shows up with an appropriate picture or a movie, even when those movies just may be a series of images showed one after the other, and then getting the stats of the wonder displayed as the last image of the movie, same for when founding a religion or discovering a natural wonder.

**Comment by alberts2** [comment]
That screen only popped up if the wonder had a movie tag but lots of then didn't have a movie. You never got that screen for lots of wonders.
But i think some had a empty movie define which lead to displaying the screen without a movie playing.

**Comment by Toffer90** [comment]
Lots is an overstatement, the huge majority of wonders had a functioning movie of some kind.
All natural wonders had it too, but here it makes far more sense to use a .dds file for sure.
I think all religions had a movie when being founded.

**Comment by billw2012** [comment]
I think we can add them back in to the Assets\art folder and they will just work, iirc they are mostly in the 1MB or so size right? That is no problem

**Comment by Toffer90** [comment]
About 250 MB total.
I did try adding them in the art folder, but the albert bot automatically cleaned them out of there.

btw, there's no need for a new xml tag, the python code that displays the movie can look at the path ending to see if it is a .bik or a .dds and handle them based on that info.

**Comment by billw2012** [comment]
Its .gitignore file in the root folder, have a look in there you will see .bik somewhere, just remove it then git will stop ignoring the files.

**Comment by Toffer90** [comment]
I did modify the gitignore to allow it:
Changed 
- Assets/art/
- !Assets/art/Readme.txt
To:
- Assets/**/*.dds

Worked like a charm until albert reverted my push...

**Comment by billw2012** [comment]
Welp thats up to you guys to sort out, there is no technical limitation on them being in the repo though, the FPK packing etc should still work fine

**Comment by alberts2** [comment]
> Worked like a charm until albert reverted my push...
When did i do that??????

**Comment by Toffer90** [comment]
I must have imagined it, probably forgot to push yesterday when I added in all the biks on my side.

**Comment by Toffer90** [comment]
Sorry.

**Comment by alberts2** [comment]
> Lots is an overstatement, the huge majority of wonders had a functioning movie of some kind.
> All natural wonders had it too, but here it makes far more sense to use a .dds file for sure.
> I think all religions had a movie when being founded.
> I think entering a new era has a movie per era too, but these also make far more sense as a .dds file.

Depends in how you defines lots  then i remember correctly only 233 of 332 wonders in the great wonders xml had a movie tag.

**Comment by Toffer90** [comment]
I think there's enough movies to keep them in C2C. Is it ok if I add them back?

**Comment by raxo2222** [comment]
There is 269 National Wonders and 1029 world wonders. 
I searched for iMaxPlayer[Global]Instances tags in class infos.

**Comment by alberts2** [comment]
> Sorry. I was tired yesterday when I did that, and then today I saw raxo removed all the xml references to the movies, and I was sure I also saw a comment from you somewhere today about the bik files taking too much space.
> I then assumed something I shouldn't have.

No problem!

I my eyes these movies aren't worth the space they consume because some have a really questionable content but that's probably only my opinion. I wanted to keep the repo as small as possible to make working with it as fast as possible.

The upside is that there's a option to turn them all off.

**Comment by billw2012** [comment]
Maybe we should do a quality pass and just keep the good ones?

**Comment by Toffer90** [comment]
How's the best way to deal with raxo's last push that removed all the xml? 
Right click it in GK and select revert commit?

**Comment by billw2012** [comment]
yeah

**Comment by Toffer90** [comment]
Doing a quality pass at some point makes sense.

**Comment by alberts2** [comment]
Would have been good to do that quality pass before adding them because now these files are in the repo and every time you clone it you have to download all of them.

In the .gitignore adding
`!*.bik`
would have allowed adding *.bik files.
Now you can add all kinds of files like *.nif into Assets/art exept *.dds files.

**Comment by billw2012** [comment]
yeah we can do history purge later when we decide which ones to keep. i did that when doing the original SVN clone with history.

**Comment by billw2012** [comment]
Fixed in d572cbbaf4fa8967e332fb328a756590791dd273
