### ISSUE TITLE
Captive Civilians can use 'join city' action on cities owned by a vassal. Pop bonus goes to nearest city owned by player.

### ISSUE THREAD

**Issue by dzfischer** [caveman2cosmos/Caveman2Cosmos#674]
Reported by user CHOO CHOO on discord, 10/06/20:
"Bug: Civilian Captives [owned by me] joining a vassal's City instead added the population bonuses to the closest city belonging to myself, neatly ignoring that at size 19, it wouldn't have been eligible for immigration."

Possibly 'join city' action is looking at team, not player, for eligibility. Probably shouldn't be able to join vassal city at all.

**Comment by flabbert** [comment]
I remember the discussion, pretty sure his was fixed a while ago
