### ISSUE TITLE
FAssert: best build < NO_BUILD

### ISSUE THREAD

**Issue by MattOttawa** [caveman2cosmos/Caveman2Cosmos#675]
ASSERT FAILED
==============================================================================================================================================================================
File:        C:\Users\Matt\Documents\GitHub\Caveman2Cosmos\Sources\CvCityAI.cpp
Line:        9240
Expression:  m_aeBestBuild[iI] == NO_BUILD || m_aiBestBuildValue[iI] > 0
==============================================================================================================================================================================
DLL CALLSTACK:
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
sources\cvcityai.cpp (9240): CvCityAI::AI_updateBestBuild
sources\cvcityai.cpp (254): CvCityAI::AI_doTurn
sources\cvcity.cpp (1522): CvCity::doTurn
sources\cvcity.h (2368): CvCity::fn::doTurn::operator()
build\deps\microsoft visual c++ toolkit 2003\include\algorithm (21): std::for_each<CvPlayer::city_iterator,CvCity::fn::doTurn>
build\deps\boost-1.55.0\include\boost155\range\algorithm\for_each.hpp (102): boost155::range::for_each<boost155::iterator_range<CvPlayer::city_iterator>,CvCity::fn::doTurn>
sources\cvplayer.cpp (4131): CvPlayer::doTurn
sources\cvplayer.cpp (13064): CvPlayer::setTurnActive
sources\cvplayer.cpp (13178): CvPlayer::setAutoMoves
sources\cvgame.cpp (7886): CvGame::updateMoves
sources\cvgame.cpp (2557): CvGame::update
00415321 (Civ4BeyondSword): (filename not available): (function-name not available)
00686BC8 (Civ4BeyondSword): (filename not available): (function-name not available)
75BB6359 (KERNEL32): (filename not available): BaseThreadInitThunk
77097C24 (ntdll): (filename not available): RtlGetAppContainerNamedObjectPath
77097BF4 (ntdll): (filename not available): RtlGetAppContainerNamedObjectPath

**Comment by MattOttawa** [comment]
is this new?

**Comment by Toffer90** [comment]
I saw it two days ago, and wondered the same.
Can't remember seeing it before that.

**Comment by dzfischer** [comment]
Fixed by [Toffer's commit](https://github.com/caveman2cosmos/Caveman2Cosmos/commit/75eca48ff87d4bb6517589b1cfccf39c7815ce2f) a few days ago, right?

**Comment by Toffer90** [comment]
No this is another thing.
