### ISSUE TITLE
Lunar Settler loses ability to settle after the switch to tech some time after Planetary Colonization Tech

### ISSUE THREAD

**Issue by thebarbarian09** [caveman2cosmos/Caveman2Cosmos#679]
I'm late in the game now and suddenly my Lunar Settlers can create any more cities. I have two on the moon already and I was hoping to create a chain of settlements between them to pick up the resources but both Lunar Settlers trained directly from the Cislunar Colonies nor the Lunar Settlers created from converted Heavy Rockets at Space Station Lv.3s don't seem to function as they should.

**Comment by raxo2222** [comment]
You must settle on improvement:
Lunar Base or its upgrades.
