### ISSUE TITLE
Abandoning city gives negative gold

### ISSUE THREAD

**Issue by dzfischer** [caveman2cosmos/Caveman2Cosmos#690]
"Abandoning city from city menu gives negative gold (seems it is sum of all buildings but negative). And clicking this button if you dont have enough gold makes you have negative gold."

**Comment by Toffer90** [comment]
> And clicking this button if you dont have enough gold makes you have negative gold."

That would be a bug, dept is not a thing in C2C (I personally think we should allow it to go negative so that it is much harder to get out of the mire when you first hit it.)

I'll look into it,

**Comment by flabbert** [comment]
fixed?

**Comment by Toffer90** [comment]
I think so.
