### ISSUE TITLE
Text needs cleanup - spell and grammar check, lets automate it

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#74]
Spelling, incorrect capitalization.
![image](https://user-images.githubusercontent.com/1453936/64076413-8ba0cd00-ccbc-11e9-9d25-e230d9c67273.png)

**Comment by raxo2222** [comment]
There is tons of similar typos here and there.
I guess modders didn't use spellchecker.

**Comment by billw2012** [comment]
Cool well we can do auto fix on them all then I hope, normal word processor would capture and fix these two automatically.

**Comment by raxo2222** [comment]
Is it smart enough to not break translations? That is look for typos only between <english> tags.

**Comment by billw2012** [comment]
Well I'm talking about a hypothetical tool not a specific one so yeah it is smart enough to do anything :D

**Comment by billw2012** [comment]
These things together will make it so we can automate spell checking on text, I can add them to our auto-tests, and also make it so they can be run locally via a script and automatically apply fixes. Then we can check the fixes are good and commit them.

https://github.com/Findus23/pyLanguagetool
https://languagetool.org/http-api/swagger-ui/#!/default/post_check
http://wiki.languagetool.org/http-server#toc0

**Comment by billw2012** [comment]
I'm actually pretty close to this, so we can add it to v40 milestone.

**Comment by raxo2222** [comment]
You should be careful, as in Atomic and later eras stuff have more and more various neologisms and rarely used words.

**Comment by billw2012** [comment]
Yeah I'm not just going to auto-correct and then commit it, there will be plenty of places where it is wrong. In fact one of the original errors in this bug isn't picked up by ANY spell check API including the most advanced ones! So I'm going to run it then use GK to go through the changes and revert any that aren't correct. However this job might be massive, I don't know yet. If it is then I will leave it up to someone else to volunteer to do it, or we can do it piecemeal.

**Comment by billw2012** [comment]
LanguageTool is good for grammar and style but spelling is no use for our stuff (it doesn't know loads of historic and scientific nouns).
I will keep it but disable the spelling rules and instead use https://github.com/mammothb/symspellpy with a word list calculated from wikipedia (https://dumps.wikimedia.org/enwiki/latest/). I'm only going to do it for English myself, but it should be easy to do for the other languages as well.
