### ISSUE TITLE
Review ALL [LINK= entries. Some of them may lead to nonexistant stuff. 

### ISSUE THREAD

**Issue by raxo2222** [caveman2cosmos/Caveman2Cosmos#743]
Apparently lots of these are holdover from before many changes and renames.
Example: [LINK=CIVIC_COMMUNIST] in Concepts text.

**Comment by SannitaSSJ** [comment]
Question: do we want to _remove_ the links or _fix_ them? (I can try to do my part in this)

**Comment by raxo2222** [comment]
> 
> 
> Question: do we want to _remove_ the links or _fix_ them? (I can try to do my part in this)

Remove them, since whatever they referenced no longer exists now.

**Comment by SannitaSSJ** [comment]
I've started a check on links and, just to make an example, `[LINK=UNIT_STORY_TELLER]` should be working because the unit exists... Do we want to do a double check first?

**Comment by raxo2222** [comment]
Yes
