### ISSUE TITLE
Nature Preserve cannot be built on Natural Wonders

### ISSUE THREAD

**Issue by dzfischer** [caveman2cosmos/Caveman2Cosmos#803]
`<FeatureMakesValid>` from improvementInfo tag could overrule `<bNoImprovement>` from featureInfo tag such that Nature Preserve improvement can be constructed on natural wonders; there may need to be a corresponding edit to prevent resource discovery from Nature Preserve on natural wonders.

Likely are a few places that `isNoImprovement` is called that'll need minor edits with this suggested implementation.

**Comment by raxo2222** [comment]
It seems to be partially done according to Toffer?

**Comment by Toffer90** [comment]
<bNoImprovement> still override <FeatureMakesValid>.

**Comment by raxo2222** [comment]
Oh you said its exception, when I posted screenshot of Nature Preserve being buildable on feature, that can't have any features.

**Comment by Toffer90** [comment]
> Oh you said its exception, when I posted screenshot of Nature Preserve being buildable on feature, that can't have any features.

It's intended to be the exception, I hadn't looked in code whether it worked as intended or not when I said that.
I'll push a small change that should fix the oversight.

**Comment by Toffer90** [comment]
@raxo2222 Would you be so kind to check if nature preserve now can be built on natural wonders?
