### ISSUE TITLE
"Bark Working" - Voiceover quote doesn't match text quote

### ISSUE THREAD

**Issue by briaguya-ai** [caveman2cosmos/Caveman2Cosmos#903]
the vo was something like "idols of wood and stone, idols of flesh and blood"

the quote on screen is "Twas on the inner bark, stripped..." - Thomas d'Urfee

this was on v41-2

**Comment by khalighnayao** [comment]
Philo will work on this and then have it handled by blaze.

**Comment by raxo2222** [comment]
Fixed

https://github.com/caveman2cosmos/Caveman2Cosmos/commit/b017f917e4798316be547f863a715716f4f127f4
