### ISSUE TITLE
New promo line for entertainers to 'learn' myth/story/etc and allow to spread

### ISSUE THREAD

**Issue by flabbert** [caveman2cosmos/Caveman2Cosmos#932]
Will need to investigate how well introducing 100s of new promos works. Maybe instead a dynamic promotion of some kind, or some other way of tracking which myths an entertainer knows?

**Comment by raxo2222** [comment]
This is obsolete, as story teller line doesn't build myths any more - Most of folklore is buildable only trough subdued animals.
Exploration folklore is buildable in cities.
