### ISSUE TITLE
Convert myths from buildings to bonusclass resource

### ISSUE THREAD

**Issue by flabbert** [caveman2cosmos/Caveman2Cosmos#933]
Reduce # of buildings! Will likely require nontrivial refactoring/editing to ensure functionality remains the same.

**Comment by raxo2222** [comment]
Storys and stories also can be done same way

**Comment by raxo2222** [comment]
Myth effects, storys, stories, and stories effects were completely removed, and myths were renamed to Folklore
There are 237 unique folklores, also there is no need to convert those to bonuses - this would still need buildings
