### ISSUE TITLE
Update, import Toffer's changes

### ISSUE THREAD

**Issue by flabbert** [caveman2cosmos/Caveman2Cosmos#934]
Investigate balance issues, ensure smooth compat with current core

**Comment by raxo2222** [comment]
Myths were already overhauled, as they bring 0.2 beakers at start and then this bonus declines by 0.05 per lifestyle tech
Ongoing saves were possibly disrupted as old myths were removed, and now players had to recollect folklore.
Folklore spreads itself to all cities, so at 5 cities they potentially are on parity with old system.
