### ISSUE TITLE
Apply bounded exponential limits for number of myths (make general func? Future use)

### ISSUE THREAD

**Issue by flabbert** [caveman2cosmos/Caveman2Cosmos#935]
May or may not be easily integrated into myth code; would be useful for future plans regarding stories, collecting multiple cultures, etc. General function likely useful; applicable to TD at least, probably elsewhere as well.

**Comment by raxo2222** [comment]
Folklore has much lower impact on research and culture now. Also they gradually swap research with culture on lifestyle techs.
Exploration and Taxonomy gain Education at certain techs - they now act as autonomous stories
