### ISSUE TITLE
Wrong calculation of Pharmacy building profit

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/Caveman2Cosmos#94]
![image](https://user-images.githubusercontent.com/1453936/64270378-5651e480-cf33-11e9-9bfe-b9e9851ce5b3.png)

**Comment by raxo2222** [comment]
Could be bug in actual effects calculation in general, and this building showed it.

**Comment by billw2012** [comment]
TB said you might have some ideas about this @raxo2222

**Comment by billw2012** [comment]
And I'm an idiot who can't read 2 lines up :D

**Comment by billw2012** [comment]
@raxo2222  Didn't you leave a comment here with an explanation at some point?

**Comment by billw2012** [comment]
Save game here: https://cdn.discordapp.com/attachments/519722458778042379/618867928590188584/Argalgane_April_4_AD-0752.CivBeyondSwo

**Comment by raxo2222** [comment]
I tried, but apparently it was just restating what was shown here, that's why I deleted it.
I don't know how to find code calculating actual value of buildings.

**Comment by raxo2222** [comment]
I think it may be part of function in CvGameTextMgr.cpp - line 22735 is beginning of function, that displays actual effects of buildings.

**Comment by billw2012** [comment]
So this is a data issue, the calculation is correct. Pharmacy replaces apocathery, but has 5 less gold. Seems wrong, but not a code bug.
![image](https://user-images.githubusercontent.com/1453936/64388687-d3ff1880-d037-11e9-9a97-f354f90eb1ef.png)
![image](https://user-images.githubusercontent.com/1453936/64388724-e24d3480-d037-11e9-9c5b-5fe5bab946d9.png)

**Comment by Toffer90** [comment]
Ah lol, Apothecary shop is getting +5 gold from the Apothecary Guild national wonder.

**Comment by raxo2222** [comment]
So replacements must get such boost from wonders too.
It may tens of these if not hundreds.

**Comment by Toffer90** [comment]
The guild design should be discussed further, best thing to do imo is to comment out the apothecary guild national wonder for now.

**Comment by raxo2222** [comment]
https://github.com/caveman2cosmos/Caveman2Cosmos/commit/75ad982a5e29cdcc7d51c5fccc095c9836babe89
A lot of guilds were like this.
I also fixed other wonders too.
