### ISSUE TITLE
AI friendly space colonization

### ISSUE THREAD

**Issue by flabbert** [caveman2cosmos/Caveman2Cosmos#942]

**Comment by raxo2222** [comment]
This will wait until multimaps are ready

**Comment by flabbert** [comment]
Sounds like lunar colonization needs to be simplified for it to be realistic that AI can handle it, and maybe sacrifice some realism in the process.

**Comment by raxo2222** [comment]
So simple for AI colonization would be:
Just build Cislunar/Lunar settler on Earth, send it to Cislunar/Lunar space and build cislunar city (big space station effectively) anywhere.
Lunar city also could be anywhere.

Instead of making lunar worker (lunar bulldozer) on improvement by sending construction ship here, make them buildable on same tech as you can make lunar cities.

**Comment by flabbert** [comment]
Something along those lines yes.

A recurring issue in this mod is that we are trying to implement everything at once, instead of trying to do it gradually, making first version work, and then improving on it after.

**Comment by raxo2222** [comment]
Pepper wanted to add space content first and foremost.
He then was tweaking stuff, but was too busy to work on it any more.

Balance and AI weren't concerns for this stuff - there was extremely scarce space content before V37.
I then tweaked it here and there - some Mars/Moon content belonged to another inactive modder so I eventually merged it.
Now everything space related is in Pepper module, maybe except text, art and sound defines.

**Comment by flabbert** [comment]
I do understand that, but for this mod to actually be usable in these areas we should work on getting bare minimum end to end, and then start fleshing out one area at a time

**Comment by raxo2222** [comment]
When I was testing that branch where I let AI build directly linar and cislunar settlers without needing any improvements or auxiliary units, AI still didn't want to colonize space....

It looks like buildings should be completly revamped, building valuation code needs to be revamped.
Space terrains have NO base yields, which breaks some vanilla game assumptions.
On Space AI city should be like this:
Maximize yields and production. Build improvements, that will maximize development speed of city - getting up to date with buildings and have cities gaining population in reasonable time.

**Comment by flabbert** [comment]
Is there any particular reason why we cannot give Lunar yields? I mean only specific unit categories can get there anyway, and it stands to reason some kind of base yield could be possible if you have the right mobile equipment?

**Comment by raxo2222** [comment]
Possibly balance problems?
Also yields must be progressively higher for later space zones - colonies are bigger farther out.

Here is layout of space terrains, features and bonuses.
https://forums.civfanatics.com/threads/guide-to-space-map-making.656681/

**Comment by flabbert** [comment]
I am absolutely sure we will have balance issue in the beginning, the question is really, Is it easier to teach the AI to develop plots that has nothing, or teach AI that its a good idea to use the space units to get the increased yields in space.

**Comment by raxo2222** [comment]
Having yields on all plots would be nice, but even on Earth AI is kinda lazy with making cities

**Comment by flabbert** [comment]
Well that can be solved with tightening up the decision making trees for the AI, my fix to workers that ill finish up and commit later today should help with this.

**Comment by raxo2222** [comment]
I simplified early space colonization some time ago.
That is just build Space Station earthly building and make cislunar/lunar/planetary settlers.
This building effectively represents space station level 3 improvement.

Supply ships were removed, instead you can build those buildings on Moon for cheap.

You don't need improvement to settle on Moon surface anymore.

Construction ship acts as early Moon/Mars/Venus worker, and you can build Lunar Bulldozer in Lunar city when lunar settlers are unlocked. It is dedicated to resource extraction (a way to prevent construction ships from building space mines on Earth)

As for AI settlers: New Space Settler AI must be developed for AI to be capable of settling in space.
