### ISSUE TITLE
Assert Line 5414

### ISSUE THREAD

**Issue by flabbert** [caveman2cosmos/Caveman2Cosmos#943]
Line: 5414
SVN-Rev: 10998
Expression: stricmp(szType, "NONE")==0 || strcmp(szType, "")==0
Message: info type 'ADAPT_SCALE_CITY_LIMITS' not found, Current XML file is: Not found.

Problem with parsing the percent tags in world and gamespeed info types perhaps.

**Comment by Toffer90** [comment]
Never seen that assert before...

**Comment by flabbert** [comment]
closing it then, it was a comment you made way back when

**Comment by Toffer90** [comment]
> closing it then, it was a comment you made way back when

Must have forgotten about it, and it was probably also fixed way back when.
