### ISSUE TITLE
Code prettifying ruleset

### ISSUE THREAD

**Issue by flabbert** [caveman2cosmos/Caveman2Cosmos#945]
So much erroneous whitespace and misaligned tab stuff

**Comment by flabbert** [comment]
This is a catch all issue, and should be replaced with individual issues per file, but a concerted effort to improve the codebase, and agree on a set of rules should be made before v42

**Comment by MattOttawa** [comment]
https://github.com/caveman2cosmos/Caveman2Cosmos/wiki/CPP-Style-Guide

**Comment by MattOttawa** [comment]
.editorconfig is a good start. We can use it to start recording what we want.

Maybe we can delete the one in the mod directory and keep the one in the sources folder. We can add another for python later if we want.

**Comment by MattOttawa** [comment]
https://github.com/caveman2cosmos/Caveman2Cosmos/compare/boost-upgrade...caveman2cosmos:clang-format-code
