### ISSUE TITLE
MAD nukes isn't active

### ISSUE THREAD

**Issue by MattOttawa** [caveman2cosmos/Caveman2Cosmos#960]
I ran into some obvious mistakes in MADNukesManager.py

		objPlayer = GCgetPlayer(GCgetGame().getActivePlayer())
		iPlayer = GCgetGame().getActivePlayer()

		iTargetColor = GCgetInfoTypeForString("COLOR_RED")

Turns out MAD Nukes is enabled if a player has a civic with the bEnablesMADNukes tag.
No civics in C2C has this tag.

**Comment by raxo2222** [comment]
Sounds like remains of some removed feature
