### ISSUE TITLE
Worker Actions for Captive Units

### ISSUE THREAD

**Issue by flabbert** [caveman2cosmos/Caveman2Cosmos#969]
Remove Worker actions for captive units, as it is severely hampering build evaluation and worker AI.

The ability to kill a unit when completing a worker action should be in the unit, not in the build

**Comment by raxo2222** [comment]
Improvements with bKill (consume unit) build variant:
Land
Desert Camp
Jungle Camp
Wetlands Camp
Mushroom Gatherer
Salt Gatherer
Seed Camp
Stone Tools Workshop
Tar Gatherer
Seasonal Camp
Fortified Cave
Wooden Palisade
Wooden Watchtower

Water
Fishing Camp
Harvest Kelp

There are improvements, that always consume unit (only build is with bkill):
65 Bonus Placing quasi-improvements 
Great Farmer can place any land plant/animal bonus, if you have it on territory, or import it.
So Great Farmer ALWAYS can be consumed.

9 in Space Module - 3 for 3 levels of Space Station (Space Shuttle and Heavy Rocket can have kill on use tag too)
Place Asteroid and Place Galaxy are terraforming-like builds too. Those consume unit and change feature.
Build Lunar Base, Lunar Outpost, Lunar Habitation Complex, Lunar Mining Outpost also will kill unit.

29 unit killing builds in core (some with no-kill variants):
Nomadic Herd, Scavenging Camp, Fruit Gathering Camp, Grape Gathering Plant, Plant Gathering Camp, Mushroom Gatherer, Tar Gatherer, Salt Gatherer, Seed Camp, Seasonal Camp, Stone Tools Workshop, Wood Gatherer, Moai Statues, Jungle Camp, Desert Camp, Wetlands Camp, Wooden Watchtower, Fortified Cave, Palisade, Abatis Thorn, Break Ice, Whaling Ships, Whaling Boats, Fishing Boats, Fishing Camp, Harvest Kelp, Extraction Facility, Offshore Platform, Submerged Town.

It seems like we should keep bkill on improvements, but we could vastly reduce it, if ALL workers builds consume worker.

**Comment by Thunderbrd** [comment]
You can't put bkill on improvements because different units can build farms without dying.  You can't put it on units because not all builds kill gatherers (routes for example) and not all builds kill workboats though many do.

**Comment by flabbert** [comment]
You can put bKill on the build, but the fundamental bottomline here is the rework needed for AI to handle special builds, and the reason plots dont get improved is because builds exists that normal workers cant handle, but still end up in the best build list.

That is why SLAVE builds basically got to go, because they are a better build than the normal builds, but they are inaccesible to Normal worker. The result is that normal worker does not improve the plot because it doesnt have access to the build in the first place.

**Comment by Thunderbrd** [comment]
Got it... maybe the first check should place its result in a vector list and then the worker builds the best build available to that unit (assuming that nothing is already there)

**Comment by flabbert** [comment]
That is what i considered. And probably would be the end longterm result, but for first version, duplicate builds gotta go

**Comment by flabbert** [comment]
its duplicates, and MAORI that is broken at the moment. There is a bigger fundamental issue with how builds are found for an improvement that is incredibly inefficient. The improvement should know what the builds for itself are. But again that is not part of first version of a fix for this.

**Comment by Thunderbrd** [comment]
I'm not sure why you'd want to do a broken version first then slow down and do it right on a second pass?

**Comment by flabbert** [comment]
because the second pass is significantly more work, the workers have no concept of vectors, and setting up that entire chain permeates through so much of the codebase. Getting the logic fundamentally in order is a far bigger priority than trying to include captives being able to build improvements, and 1 culture improvement for AI

**Comment by Thunderbrd** [comment]
Fair 'nuff - but perhaps for now just comment out rather than nuke what doesn't work so that you have a very strong test case easily turned back on when you do put a structure together that can handle what our xml is trying (and should be able) to do.

**Comment by flabbert** [comment]
If you read what i have already written with regards to how this project is done. Then that wont be an issue.

When something is put into this project, and actually pushed into master, the PR itself, with the old data will be linked to the issue. So that we have the concept, and the data available, if and when it is put back in.

I take big issue with just leaving stuff commented out in this already incredibly bloated codebase. Work has to be done to make it more streamlined and more easily maintained. Simply commenting stuff out for fear of losing it when we have a solid versioning system in place does not make any kind of sense, and just adds to the technical debt we already have.

**Comment by Thunderbrd** [comment]
Commented out material is a hell of a lot easier to turn back on than anything requires to be compared back in btw.  It's much much more time consuming and complex to compare files that aren't much like they used to be when you removed things before.

**Comment by Thunderbrd** [comment]
You understand that how gatherers work is now fundamental to c2c right?  You can't eliminate these duplicates without screwing them up.

**Comment by flabbert** [comment]
Gatherers are not the primary issue here, captives are. 

And the overlap between gatherer working, and worker workings are really small. Using the bSuicide tag on the gatherer unit also solves that issue, since they are designed to die upon completing a build.

The fundamental issue happens when a build that worker cannot use is classified as the best build, simply because its faster than the normal build. Giving gatherers more working power, and making those kill tags take longer could solve that issue. They are still not the primary concern with evaluation and solving this problem. 

Captives being able to build the same improvement as a worker at any stage but cheaper in timeunits with its separate build action is the fundamental reason that entire build evaluation breaks (together with everything being able to upgrade, which kinda but not really have been solved)

**Comment by Thunderbrd** [comment]
Gatherers don't die when they complete a route so it's not like everything they do kills them.

That said if you think you can negotiate around it fine.

And if it's so important to stash someone's xml efforts until a later improvement makes them more possible for the code to work with, than at LEAST comment on where it can be found to be recovered again in the core files somewhere so that people don't just forget all that work is there waiting to be returned.  I get the feeling you're just arguing to remove it because you find it annoying by design.

**Comment by flabbert** [comment]
I dont care about captives one way or the other, they work for what they do, what i do care greatly about, is that things should fundamentally work. 

This does not, and the entire game suffers for it as a result.

**Comment by Thunderbrd** [comment]
yeah well, captives aren't the issue really is my point - this will cause trouble for workboats and can also, once the worker actions are validated by tech at least, will cause some conflicts with gatherers (which explains a lot about why gatherers haven't been doing the basic things they should be and thus impeding growth for the AI).

My point about the captives and their build xml is that if you just slash all that out of the xml it becomes easily lost later - a version control is not an easily accessed library of project material imo.

**Comment by flabbert** [comment]
this will not cause an issue for workboats, because there are not 2 builds that do the same thing for them,

Whenever there is a BUILD_FARM and a BUILD_FARM_KILL, which normal workers dont have access to, thats when you have the issue. Since both of them make the same improvement, but the kill version is cheaper.

**Comment by Thunderbrd** [comment]
Sucks we're stuck with gatherers having to have a faster workspeed than workers - that complicates things in a way too.  But as a temporary solution I suppose.

I would've thought workboats have this issue with ice removal.

**Comment by Thunderbrd** [comment]
Well yeah, that's what I'm worried about is all the cases that haven't been thought of lol.  It sounds like you're NOT planning to go back and make sure this is done right and it will become yet another forgotten known project we need to do 'someday'.  I get the incremental improvement method - I just try to avoid using it myself because I end up with a lot of forgotten frayed edges that way.  Don't take this as any kind of criticism.  Two people are going to think and have to work with their patience levels in different ways - I get that.

**Comment by raxo2222** [comment]
What about array type build action?
That is:
<build>
     XXXX
     bkill = 1
</build>
<build>
     YYYYY
     bkill = 0
</build>
This way unit would be killed only on selected builds
